# Integrated Project: Maji Ndogo Part 3

## Maji Ndogo: From analysis to action
# Weaving the data threads of Maji Ndogo's narrative

> ⚠️ This notebook will not run on Google Colab because it cannot connect to a local database. Please make sure that this notebook is running on the same local machine as your MySQL Workbench installation and MySQL `mdd_water_services` database.




### Subject: Results of audit on Maji Ndogo water project

For clarity, in this specific audit, our objective was to assess the integrity, and accuracy of the data stored in the database. Auditing a database
involves verifying that the data it contains is both accurate and has not been tampered with, thereby ensuring that the information can be relied
upon for decision-making and governance.

I am pleased to report that the audit is now complete. After a rigorous examination of the database's records, as well as the procedures in place for
data entry and modification, we can confirm that the vast majority of the data aligns with the principles of good governance and data-driven
decision-making that you have so vigorously championed.

## ERD in MySql

Hey! It's been a while! I hope you are ready to get stuck in. We got back the auditor's report, so we need to compare their results to ours.

To integrate the auditor's report, we will need to access many of the tables in the database, so it is important to understand the database structure.
To do this we really need to understand the relationships first, so we know where to pull information from.

### Note that
the visits table is the central table. location_id, source_id and assigned_employee_id are primary keys in their respective tables,
but are all foreign keys in visits. These are mostly dsone-to-many relationships. Let's think some of these through so we are sure this is correct.

The visits table logs all the times we've been to different places, and we can see that some locations have been visited multiple times. On the
other hand, the location table has all the specifics about each place we've been but it only includes each location once. So, it's a one-to-many
relationship: for each unique location in the location table, there might be many corresponding records in the visits table detailing all the
different times we went there.

Let's look at the relationship between the visits and water_quality tables. For every entry in the visits table, there should be one unique
corresponding record in the water_quality table. This means each visit recorded is associated with a specific water quality score, ensuring a
one-to-one relationship between the visits and water_quality tables.

But if we look at the ERD, it shows a many-to-one relationship. This does not agree with our thinking. Errors like these can cause problems, so let's
fix that.

We should normally be careful making a change like this. First you should check that record_id is unique for both tables, and are indeed
one-to-one but I did that.

## Connecting to our MySQL database

Using our `Access_to_Basic_Services` table created in MySQL Workbench, we want to answer some questions on the range of our dataset. We can apply the same queries in MySQL Workbench and in this notebook if we connect to our MySQL server. Since we have a MySQL database, we can connect to it using mysql and pymysql.

In [13]:
# To display all row in ouputs
%config SqlMagic.displaylimit = None

In [14]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [15]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:data@localhost:3306/md_water_services

'Connected: root@md_water_services'

#### Integrating the Auditor's report
Ok, I have a .csv file of the auditor's results. I loaded it into MYSQL.

In [5]:
%%sql
-- To make sure we have the same names, use this query to create the table first, then Import the CSV file:
 
CREATE TABLE `auditor_report` (
         `location_id` VARCHAR(32),
         `type_of_water_source` VARCHAR(64),
         `true_water_source_score` int DEFAULT NULL,
         `statements` VARCHAR(255)
           )     
-- I did it in mysql and import the csv file called auditor_report

 * mysql+pymysql://root:***@localhost:3306/md_water_services
(pymysql.err.OperationalError) (1050, "Table 'auditor_report' already exists")
[SQL: -- To make sure we have the same names, use this query to create the table first, then Import the CSV file:

CREATE TABLE `auditor_report` (
         `location_id` VARCHAR(32),
         `type_of_water_source` VARCHAR(64),
         `true_water_source_score` int DEFAULT NULL,
         `statements` VARCHAR(255)
           )
-- I did it in mysql and import the csv file called auditor_report]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Wow! First off, it looks like we have 1620 records, or sites that they re-visited. I see a location_id, type of water source at that location, and the
quality score of the water source, that is now independently measured. Our auditor also investigated each site a bit by speaking to a few locals.
Their statements are also captured in his results.

We need to tackle a couple of questions here.
1. Is there a difference in the scores?
2. If so, are there patterns?

For the first question, we will have to compare the quality scores in the water_quality table to the auditor's scores. The auditor_report table
used location_id, but the quality scores table only has a record_id we can use. The visits table links location_id and record_id, so we
can link the auditor_report table and water_quality using the visits table.

In [17]:
%%sql
SELECT
     location_id,
	 true_water_source_score
FROM
    md_water_services.auditor_report

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1620 rows affected.

[('SoRu34980', 1),
 ('AkRu08112', 3),
 ('AkLu02044', 0),
 ('AkHa00421', 3),
 ('SoRu35221', 0),
 ('HaAm16170', 1),
 ('AkRu04812', 3),
 ('AkRu08304', 3),
 ('AkRu05107', 2),
 ('AkRu05215', 3),
 ('HaDe16541', 2),
 ('KiRu30351', 9),
 ('AmAm09813', 4),
 ('SoRu37005', 0),
 ('KiRu26067', 3),
 ('SoRu37100', 0),
 ('AmDa11611', 1),
 ('KiRu29290', 3),
 ('AkRu07801', 3),
 ('KiZu31015', 3),
 ('KiIs24026', 2),
 ('AkRu08480', 2),
 ('AmBe11043', 3),
 ('AmRu13718', 9),
 ('AmRu15209', 3),
 ('SoRu37428', 3),
 ('SoRu34787', 2),
 ('AkRu03204', 3),
 ('SoMa34137', 3),
 ('SoRu38874', 3),
 ('KiMr24320', 2),
 ('AkRu06460', 2),
 ('KiHa22748', 9),
 ('KiRu28673', 1),
 ('AkHa00193', 9),
 ('AmAs10732', 0),
 ('KiRu27585', 3),
 ('AkRu03541', 2),
 ('AkRu04448', 3),
 ('HaRu20155', 0),
 ('AmAm09990', 5),
 ('KiZu31024', 0),
 ('SoIl32392', 3),
 ('SoRu38699', 3),
 ('KiAm22079', 9),
 ('KiRu26316', 3),
 ('AkKi01456', 9),
 ('AkRu08152', 2),
 ('KiRu27444', 7),
 ('HaRu20693', 1),
 ('AkRu04981', 3),
 ('KiRu28580', 1),
 ('KiRu30008', 1),
 ('SoMa34631', 2),
 ('SoKo33227', 1),
 ('AmRu14465', 3),
 ('AkHa00008', 3),
 ('HaRu19826', 9),
 ('AmDa11947', 1),
 ('AmPw12680', 3),
 ('SoRu37841', 6),
 ('KiRu27884', 1),
 ('HaDe16514', 1),
 ('KiMr24591', 0),
 ('KiIs24014', 1),
 ('AkRu07523', 3),
 ('KiZu31170', 9),
 ('AkRu04753', 9),
 ('SoRu36774', 2),
 ('SoRu36239', 2),
 ('KiRu27776', 3),
 ('AkRu03164', 3),
 ('AkRu05809', 2),
 ('KiRu28632', 5),
 ('KiRu30389', 4),
 ('AkKi01375', 3),
 ('SoRu37530', 0),
 ('AmBe10959', 4),
 ('HaRu19828', 2),
 ('SoIl32999', 2),
 ('HaRu18571', 2),
 ('AkRu08666', 6),
 ('AkRu03306', 7),
 ('AkRu08936', 3),
 ('HaSe21341', 3),
 ('SoRu35327', 1),
 ('AmRu14903', 9),
 ('AmAb09101', 6),
 ('KiAm22276', 0),
 ('HaRu20617', 1),
 ('KiZu31370', 3),
 ('HaRu18217', 1),
 ('KiRu29806', 9),
 ('KiRu28057', 1),
 ('AkRu06170', 3),
 ('AkRu03380', 3),
 ('KiRu26678', 2),
 ('AmBe10942', 9),
 ('KiIs23730', 3),
 ('KiHa23034', 3),
 ('AkRu06495', 2),
 ('HaRu17528', 1),
 ('KiRu28090', 6),
 ('AmRu13729', 2),
 ('HaRu18016', 1),
 ('KiRu27440', 9),
 ('HaYa21606', 3),
 ('HaRu17207', 1),
 ('AmAm09735', 1),
 ('HaRu20534', 2),
 ('SoRu38331', 3),
 ('AmPw12770', 3),
 ('AkLu02096', 3),
 ('HaRu20434', 2),
 ('AkRu02688', 0),
 ('AmBe11285', 9),
 ('AmRu13720', 3),
 ('SoMa33819', 0),
 ('SoRu38119', 1),
 ('AmRu12983', 3),
 ('SoRu35906', 5),
 ('KiRu27742', 3),
 ('SoRu35991', 3),
 ('KiRu28083', 4),
 ('AmRu15159', 9),
 ('HaYa21456', 2),
 ('HaRu18734', 2),
 ('SoRu35970', 3),
 ('AmAs10285', 3),
 ('AmRu15556', 9),
 ('KiZu31223', 3),
 ('SoRu38546', 9),
 ('AmPw12293', 6),
 ('SoRu39488', 3),
 ('SoRu39408', 5),
 ('HaRu17750', 2),
 ('AmAm09607', 9),
 ('KiRu30604', 0),
 ('KiZu30905', 9),
 ('SoRu39374', 9),
 ('AkHa00314', 9),
 ('SoRu37406', 2),
 ('AkRu05212', 9),
 ('SoIl32294', 0),
 ('AmBe11313', 0),
 ('SoRu35426', 3),
 ('AkHa00073', 3),
 ('SoRu35899', 9),
 ('KiRu26664', 2),
 ('SoRu36580', 3),
 ('KiRu26598', 9),
 ('AkLu02432', 2),
 ('HaRu19287', 5),
 ('SoRu38915', 1),
 ('KiRu26032', 0),
 ('KiRu25619', 3),
 ('KiIs23853', 2),
 ('AkHa00172', 2),
 ('KiRu27927', 3),
 ('KiRu28045', 2),
 ('KiRu29614', 1),
 ('KiRu25484', 1),
 ('AkRu04989', 1),
 ('AkKi01455', 3),
 ('SoIl33047', 2),
 ('SoCh32025', 0),
 ('KiRu28089', 0),
 ('AkRu07622', 2),
 ('KiRu29909', 1),
 ('AmBe11266', 9),
 ('AkRu03475', 1),
 ('KiRu26934', 2),
 ('SoRu35691', 5),
 ('SoMa34148', 2),
 ('AmRu15860', 1),
 ('SoRu38125', 5),
 ('AkLu02637', 9),
 ('KiIs24083', 2),
 ('SoRu35824', 1),
 ('KiRu27806', 0),
 ('AkRu03182', 3),
 ('AkHa00088', 1),
 ('SoRu36828', 2),
 ('AkLu02438', 9),
 ('SoRu38250', 6),
 ('AkHa00613', 3),
 ('KiMr25005', 0),
 ('AkRu04428', 3),
 ('SoRu35103', 5),
 ('SoRu36975', 0),
 ('AkHa00662', 2),
 ('SoCh31985', 3),
 ('AmAm09631', 9),
 ('SoRu37129', 0),
 ('SoRu38416', 3),
 ('AkRu02670', 2),
 ('AkHa00487', 3),
 ('SoRu36186', 0),
 ('AkRu03649', 2),
 ('KiRu30343', 2),
 ('AmRu13668', 9),
 ('SoMa34044', 0),
 ('AmRu14531', 9),
 ('SoRu37317', 2),
 ('KiIs23613', 6),
 ('SoRu39288', 0),
 ('AkRu07820', 3),
 ('AkRu07774', 3),
 ('SoBa31691', 0),
 ('SoRu36385', 2),
 ('KiIs24054', 9),
 ('KiRu29129', 1),
 ('KiHa23042', 1),
 ('AkHa00459', 1),
 ('SoBa31659', 3),
 ('KiRu30394', 4),
 ('SoKo33111', 1),
 ('AkRu03429', 3),
 ('KiRu26860', 0),
 ('KiAm22303', 9),
 ('HaRu18493', 3),
 ('HaRu18608', 1),
 ('SoRu35964', 2),
 ('KiMr24872', 2),
 ('KiAm22458', 2),
 ('AkRu05603', 3),
 ('HaRu20851', 9),
 ('KiRu25343', 1),
 ('SoRu36816', 3),
 ('HaRu20840', 3),
 ('SoRu38966', 5),
 ('SoRu37494', 9),
 ('HaRu19176', 1),
 ('AmBe11175', 3),
 ('HaDe16360', 1),
 ('AmBe11054', 9),
 ('AkRu08460', 2),
 ('SoKo33124', 3),
 ('AkKi01211', 3),
 ('SoIl32445', 2),
 ('AmRu13532', 9),
 ('SoRu36142', 1),
 ('AkRu05020', 3),
 ('HaRu18730', 1),
 ('KiRu25527', 2),
 ('AkRu05442', 3),
 ('AkRu05207', 3),
 ('AmAm09844', 9),
 ('AkRu04217', 3),
 ('SoRu38733', 5),
 ('SoBa31655', 9),
 ('SoRu37392', 4),
 ('AkKi01238', 3),
 ('AmRu14527', 3),
 ('KiRu26502', 3),
 ('AkRu06339', 0),
 ('SoRu37920', 0),
 ('AkRu02682', 2),
 ('AmBe10969', 3),
 ('AkRu08755', 3),
 ('KiRu30051', 2),
 ('HaRu19054', 2),
 ('HaRu17182', 1),
 ('AmBe11275', 3),
 ('HaRu19036', 2),
 ('KiMr24348', 2),
 ('AmPw12550', 9),
 ('HaRu20299', 2),
 ('KiRu29119', 1),
 ('AkRu03116', 3),
 ('SoRu35393', 1),
 ('AkLu02173', 1),
 ('AkRu08283', 3),
 ('KiRu28782', 3),
 ('AmAs10095', 3),
 ('KiRu29980', 1),
 ('KiRu25770', 3),
 ('AmRu15634', 3),
 ('AkRu07742', 2),
 ('KiRu28806', 1),
 ('AmAs10011', 9),
 ('KiMr25056', 1),
 ('HaDj16864', 1),
 ('AkRu04116', 3),
 ('AmPw12272', 9),
 ('HaRu18271', 1),
 ('HaAm16293', 3),
 ('KiRu27852', 2),
 ('AmAs10552', 9),
 ('HaAm16112', 2),
 ('KiZu30983', 3),
 ('SoRu37524', 3),
 ('HaYa21356', 2),
 ('AkRu03754', 3),
 ('SoMa34566', 2),
 ('AmRu15394', 1),
 ('HaRu19917', 9),
 ('SoRu35762', 1),
 ('AmAm09806', 9),
 ('AmAm09566', 9),
 ('KiRu27527', 2),
 ('SoRu36079', 0),
 ('AkLu02420', 2),
 ('SoRu38360', 0),
 ('KiIs23815', 2),
 ('AmRu14691', 2),
 ('AkLu01944', 3),
 ('SoBa31866', 1),
 ('AkRu05799', 3),
 ('KiRu26647', 1),
 ('AmRu14452', 3),
 ('AkRu03095', 3),
 ('SoRu37072', 1),
 ('SoBa31473', 2),
 ('SoRu35606', 3),
 ('KiRu28515', 2),
 ('KiMr24897', 9),
 ('AkRu03657', 2),
 ('KiRu29556', 2),
 ('AmAs10840', 9),
 ('SoRu37224', 2),
 ('HaRu20820', 2),
 ('KiIs23717', 3),
 ('HaRu18196', 1),
 ('KiRu28445', 1),
 ('AkRu04790', 9),
 ('AkLu01749', 3),
 ('SoRu35924', 2),
 ('KiRu27827', 2),
 ('AmRu13018', 5),
 ('SoRu36421', 0),
 ('KiRu28584', 1),
 ('KiRu29073', 2),
 ('AkHa00593', 2),
 ('AkKi01372', 3),
 ('AkLu02206', 3),
 ('AkRu08105', 2),
 ('AkRu04781', 2),
 ('KiRu27348', 1),
 ('AkRu07358', 3),
 ('SoRu35645', 3),
 ('HaDj16729', 1),
 ('AmAm09422', 9),
 ('KiRu28871', 9),
 ('SoKo33489', 2),
 ('KiIs24061', 2),
 ('SoRu36514', 6),
 ('SoRu38062', 0),
 ('AkRu04644', 3),
 ('AkRu07669', 2),
 ('KiMr24651', 3),
 ('SoRu35689', 0),
 ('KiZu31427', 9),
 ('KiMr24677', 1),
 ('KiZu30847', 9),
 ('HaRu17145', 1),
 ('SoKo33450', 2),
 ('AkRu06471', 2),
 ('AkRu03909', 6),
 ('SoRu38054', 0),
 ('KiZu30933', 0),
 ('AmRu15659', 3),
 ('AkRu04196', 1),
 ('HaRu17171', 3),
 ('KiZu31286', 5),
 ('KiRu27045', 9),
 ('AkRu07822', 2),
 ('SoRu38801', 5),
 ('AkRu05622', 2),
 ('AmRu13368', 3),
 ('KiRu29197', 2),
 ('KiHa22987', 2),
 ('AmAb09209', 0),
 ('SoRu35737', 1),
 ('HaRu20358', 1),
 ('SoRu38427', 0),
 ('SoRu39385', 2),
 ('KiAm22078', 3),
 ('HaRu18624', 2),
 ('AkLu01620', 3),
 ('SoRu39442', 0),
 ('AmBe11161', 3),
 ('AkHa00363', 0),
 ('SoRu36982', 9),
 ('KiRu29202', 3),
 ('KiRu30289', 1),
 ('HaDj16691', 3),
 ('SoRu35904', 0),
 ('AkRu07627', 7),
 ('AkRu06941', 9),
 ('SoMa33925', 1),
 ('KiAm22052', 3),
 ('SoRu37929', 0),
 ('HaRu19467', 1),
 ('HaRu19164', 1),
 ('HaRu18836', 9),
 ('SoRu38150', 9),
 ('AmAm09853', 9),
 ('SoRu38947', 2),
 ('AmDa11683', 4),
 ('SoBa31761', 2),
 ('AmRu14207', 1),
 ('HaZa21638', 1),
 ('KiRu30052', 2),
 ('KiRu26263', 9),
 ('AmAb08975', 9),
 ('SoRu38924', 9),
 ('KiRu26698', 9),
 ('KiRu26909', 3),
 ('SoCh32037', 0),
 ('SoMa33775', 0),
 ('HaRu20481', 2),
 ('KiRu29745', 2),
 ('KiRu29612', 2),
 ('AmRu13754', 9),
 ('SoRu35482', 0),
 ('HaRu17297', 9),
 ('SoKo33094', 0),
 ('AkRu03158', 9),
 ('AkRu06069', 7),
 ('KiRu26010', 1),
 ('KiRu28019', 2),
 ('KiRu30518', 3),
 ('AkRu07026', 9),
 ('KiRu26412', 0),
 ('SoRu35634', 3),
 ('AkHa00746', 1),
 ('SoIl33036', 1),
 ('AkRu06836', 1),
 ('HaRu19773', 9),
 ('KiMr24471', 0),
 ('KiRu28420', 1),
 ('AkRu07739', 3),
 ('KiRu27252', 2),
 ('KiIs23560', 1),
 ('KiRu25537', 3),
 ('KiHa23219', 2),
 ('AkLu02008', 0),
 ('SoMa34421', 3),
 ('SoRu37753', 2),
 ('AmPw12576', 7),
 ('AmRu13851', 3),
 ('KiMr24804', 5),
 ('AmAm09946', 9),
 ('KiAm22279', 3),
 ('AkRu03992', 2),
 ('AmRu14758', 9),
 ('AmRu13619', 9),
 ('AmAm09492', 9),
 ('AkRu08500', 3),
 ('HaRu18780', 1),
 ('SoRu38398', 3),
 ('AmAm09540', 0),
 ('AkLu02114', 3),
 ('AmBe11296', 3),
 ('AkRu05627', 7),
 ('AkKi01158', 3),
 ('KiRu30069', 3),
 ('AmAm09774', 9),
 ('HaRu19731', 3),
 ('AkRu07991', 2),
 ('HaZa21811', 1),
 ('AmPw12299', 9),
 ('HaRu17417', 2),
 ('AmRu12818', 3),
 ('HaSe21323', 3),
 ('AmAm09730', 9),
 ('HaAm16072', 2),
 ('KiAm22564', 0),
 ('AkRu04359', 3),
 ('AmRu14130', 2),
 ('AmPw12685', 3),
 ('AmDa11466', 1),
 ('KiIs23737', 9),
 ('AkRu05675', 3),
 ('KiRu27273', 3),
 ('KiZu31183', 9),
 ('HaRu17038', 2),
 ('HaZa21677', 1),
 ('AkKi01487', 1),
 ('AmDa12045', 5),
 ('HaDj16928', 2),
 ('SoIl32627', 3),
 ('AkRu03179', 5),
 ('AkRu05546', 0),
 ('AmAs10264', 9),
 ('AmAb08995', 9),
 ('AkRu06775', 2),
 ('SoRu35734', 2),
 ('AkRu05280', 3),
 ('SoRu35119', 2),
 ('KiRu25483', 6),
 ('KiAm22240', 9),
 ('AkRu06232', 2),
 ('KiRu25576', 6),
 ('SoRu39485', 1),
 ('AkRu07003', 3),
 ('SoRu38178', 3),
 ('HaRu18408', 3),
 ('KiRu26522', 3),
 ('KiRu28005', 2),
 ('AkRu08633', 3),
 ('AkLu01598', 2),
 ('AmPw12594', 9),
 ('SoRu39617', 9),
 ('HaRu18732', 2),
 ('AkRu04678', 3),
 ('AmRu15262', 0),
 ('KiZu30898', 3),
 ('AkRu06383', 3),
 ('KiRu29989', 9),
 ('SoRu35998', 1),
 ('AkRu04153', 2),
 ('SoMa34162', 3),
 ('KiRu27364', 0),
 ('KiRu29836', 7),
 ('SoRu35504', 2),
 ('SoRu35596', 9),
 ('AkRu04215', 1),
 ('HaZa21907', 1),
 ('AkRu05411', 0),
 ('AkRu05880', 7),
 ('AkKi01559', 3),
 ('KiMr24656', 1),
 ('HaRu17951', 3),
 ('KiRu29143', 7),
 ('AkRu04294', 9),
 ('SoKo33149', 1),
 ('AkRu04720', 2),
 ('KiRu25511', 9),
 ('SoRu35939', 1),
 ('HaRu17470', 1),
 ('KiAm22039', 3),
 ('SoRu38185', 2),
 ('KiMr25042', 4),
 ('SoRu37208', 1),
 ('KiRu29696', 2),
 ('AkKi01424', 3),
 ('AkRu03770', 7),
 ('HaZa21810', 1),
 ('AkRu03265', 3),
 ('AmAb09118', 2),
 ('AkKi01512', 3),
 ('AkRu05299', 2),
 ('AkKi00885', 3),
 ('HaRu20039', 1),
 ('AkKi01541', 3),
 ('AkHa00058', 3),
 ('SoRu36804', 4),
 ('AkRu06181', 6),
 ('KiRu30244', 1),
 ('SoRu35370', 0),
 ('KiHa22708', 2),
 ('AkKi01235', 0),
 ('HaRu17273', 1),
 ('SoRu35584', 2),
 ('HaRu17358', 2),
 ('HaYa21508', 2),
 ('SoRu36839', 3),
 ('HaAm15940', 0),
 ('KiHa23374', 2),
 ('KiRu25462', 2),
 ('SoRu39299', 1),
 ('AmRu15113', 3),
 ('KiRu25467', 0),
 ('KiMr25069', 3),
 ('HaRu18669', 1),
 ('KiMr24993', 9),
 ('KiRu29205', 5),
 ('AkRu04281', 0),
 ('AkRu03009', 2),
 ('AkRu07584', 0),
 ('KiAm22619', 3),
 ('KiHa23324', 1),
 ('SoCh32105', 0),
 ('SoRu36947', 6),
 ('AkKi01226', 2),
 ('SoMa34203', 9),
 ('AkRu07928', 3),
 ('AmAm09716', 3),
 ('KiRu26898', 2),
 ('SoRu35204', 3),
 ('SoRu38992', 1),
 ('KiRu29642', 2),
 ('KiAm22546', 0),
 ('AkRu08709', 4),
 ('AmBe11146', 9),
 ('SoRu38840', 9),
 ('HaSe20913', 9),
 ('AkRu06409', 3),
 ('KiAm22010', 9),
 ('KiRu28681', 2),
 ('KiRu27445', 0),
 ('KiMr25066', 2),
 ('AkRu08527', 2),
 ('AkRu03366', 3),
 ('AmAs10727', 3),
 ('SoCh32218', 9),
 ('HaAm16144', 2),
 ('HaDe16554', 9),
 ('KiRu27065', 0),
 ('KiRu28451', 1),
 ('SoRu36896', 4),
 ('HaYa21537', 9),
 ('AmBe11144', 9),
 ('AmAm09885', 9),
 ('AkRu04239', 2),
 ('AkRu03485', 2),
 ('HaRu20552', 9),
 ('KiRu26022', 9),
 ('SoRu37386', 5),
 ('KiRu27731', 3),
 ('AmRu14200', 1),
 ('AmRu14220', 3),
 ('HaRu18473', 2),
 ('KiRu28208', 3),
 ('AmPw12359', 9),
 ('KiIs23579', 2),
 ('SoRu36686', 9),
 ('HaRu17704', 2),
 ('AkRu07773', 3),
 ('HaRu19574', 3),
 ('SoRu35147', 2),
 ('KiRu25784', 3),
 ('HaRu20497', 3),
 ('SoRu35551', 9),
 ('AkLu02036', 9),
 ('KiRu28450', 1),
 ('AkRu05101', 3),
 ('AmRu14915', 0),
 ('SoRu38818', 0),
 ('KiRu25975', 1),
 ('HaRu19522', 1),
 ('AkRu08361', 3),
 ('HaRu19320', 2),
 ('KiRu26049', 2),
 ('KiAm22582', 2),
 ('HaAm16010', 5),
 ('SoRu37252', 2),
 ('AkRu07426', 3),
 ('KiRu28377', 2),
 ('HaDj16807', 9),
 ('HaRu20530', 2),
 ('HaRu20853', 3),
 ('KiZu31112', 1),
 ('SoRu36282', 2),
 ('AmDa11755', 7),
 ('KiAm22311', 3),
 ('KiMr24308', 3),
 ('AmRu13413', 3),
 ('AmAs10324', 9),
 ('KiRu27828', 1),
 ('SoIl32437', 3),
 ('AkRu04426', 2),
 ('AkRu06169', 3),
 ('AkRu02962', 3),
 ('AmAs10124', 6),
 ('HaRu19669', 2),
 ('KiMr25223', 1),
 ('HaRu20816', 1),
 ('AmRu13356', 9),
 ('KiIs23593', 1),
 ('AmAm09674', 9),
 ('SoRu39643', 1),
 ('AmRu15683', 9),
 ('AkRu05848', 3),
 ('AkLu02496', 3),
 ('SoRu38216', 3),
 ('KiRu30508', 1),
 ('KiRu27437', 4),
 ('KiRu28942', 2),
 ('KiAm22113', 3),
 ('AkRu04557', 3),
 ('HaRu18150', 1),
 ('AmRu15160', 2),
 ('HaRu20728', 1),
 ('KiRu26051', 3),
 ('KiRu28827', 1),
 ('HaRu17079', 3),
 ('KiRu29851', 3),
 ('AkRu08820', 3),
 ('AkRu06788', 3),
 ('AmRu13599', 9),
 ('SoMa34196', 9),
 ('AmRu15096', 9),
 ('SoIl32791', 0),
 ('AmBe11095', 9),
 ('AmAs10055', 6),
 ('AmAs10340', 9),
 ('SoRu35914', 2),
 ('SoRu36773', 1),
 ('KiHa23146', 7),
 ('SoRu35843', 0),
 ('AmDa12143', 3),
 ('HaRu18377', 4),
 ('KiMr25238', 3),
 ('AkHa00453', 3),
 ('SoRu36476', 3),
 ('KiRu26765', 3),
 ('AmBe11088', 5),
 ('KiZu31050', 2),
 ('KiRu30321', 2),
 ('SoRu38869', 3),
 ('AmAs10935', 3),
 ('SoRu37885', 3),
 ('KiRu25876', 1),
 ('HaRu18142', 2),
 ('AkRu06814', 2),
 ('KiRu25869', 3),
 ('AmAs10230', 2),
 ('AmRu14595', 3),
 ('KiAm21997', 9),
 ('SoRu35287', 2),
 ('SoRu36884', 0),
 ('HaRu19312', 2),
 ('SoRu39304', 0),
 ('KiZu30908', 0),
 ('AmAm09821', 0),
 ('AkRu03660', 3),
 ('AkHa00113', 3),
 ('KiRu28313', 2),
 ('SoBa31598', 3),
 ('KiRu26657', 9),
 ('AkRu04314', 0),
 ('HaAm16199', 1),
 ('KiRu28294', 5),
 ('AkRu08008', 2),
 ('HaRu18060', 1),
 ('AkRu06284', 3),
 ('AmRu14948', 3),
 ('SoCh32004', 1),
 ('AmRu14988', 2),
 ('AmRu13124', 9),
 ('AkRu03153', 3),
 ('KiRu25347', 2),
 ('HaSe21212', 3),
 ('SoRu36289', 1),
 ('AkLu02228', 2),
 ('AkRu08808', 6),
 ('AmAb09153', 6),
 ('AmRu15793', 2),
 ('KiRu29014', 1),
 ('SoRu39229', 4),
 ('KiRu29503', 9),
 ('SoRu36266', 2),
 ('AkRu05361', 0),
 ('KiMr25160', 2),
 ('HaRu20437', 3),
 ('AkRu07633', 2),
 ('KiZu31150', 3),
 ('AmDa11554', 5),
 ('AmRu14364', 2),
 ('KiRu26928', 2),
 ('AmPw12323', 0),
 ('KiHa23217', 2),
 ('KiZu31100', 3),
 ('SoRu37942', 1),
 ('KiHa22705', 3),
 ('AmAs10704', 9),
 ('HaRu20407', 2),
 ('KiRu29537', 2),
 ('AmRu15051', 7),
 ('KiRu30027', 1),
 ('HaRu18920', 1),
 ('AkRu06193', 3),
 ('AmRu13603', 3),
 ('AkRu05736', 3),
 ('AkRu05049', 3),
 ('SoRu36495', 1),
 ('KiIs24165', 2),
 ('KiHa22801', 1),
 ('KiRu30402', 1),
 ('AkRu07212', 3),
 ('SoMa33737', 2),
 ('AkRu05996', 1),
 ('SoRu37485', 1),
 ('HaRu18692', 3),
 ('AmDa12115', 1),
 ('SoBa31675', 9),
 ('KiRu27091', 3),
 ('SoIl32343', 6),
 ('AkRu03973', 3),
 ('AkRu06469', 3),
 ('AkRu02879', 3),
 ('HaSe21180', 1),
 ('AkRu04129', 3),
 ('AkRu03049', 3),
 ('KiRu26019', 2),
 ('AkRu05567', 2),
 ('AmRu13392', 9),
 ('KiRu29277', 6),
 ('KiHa22725', 1),
 ('AkRu07750', 3),
 ('HaRu18221', 2),
 ('AkRu03866', 3),
 ('AmAm09904', 9),
 ('AkRu05381', 6),
 ('SoRu36309', 0),
 ('SoIl32516', 2),
 ('SoRu38501', 7),
 ('KiMr24550', 9),
 ('KiRu25794', 3),
 ('KiRu29013', 2),
 ('SoRu34827', 0),
 ('KiAm22034', 9),
 ('AmRu13070', 3),
 ('AkRu05973', 3),
 ('AkRu08930', 2),
 ('AkRu05986', 3),
 ('SoRu38405', 0),
 ('KiRu25582', 3),
 ('KiMr24938', 3),
 ('KiRu27187', 2),
 ('KiRu29008', 2),
 ('AkRu06851', 3),
 ('AmRu14096', 9),
 ('SoKo33333', 2),
 ('HaDe16498', 1),
 ('AmRu15671', 0),
 ('AkRu02917', 7),
 ('AkRu08658', 0),
 ('KiHa23098', 9),
 ('KiRu27709', 2),
 ('SoKo33173', 3),
 ('KiRu29070', 1),
 ('KiRu26448', 3),
 ('AkRu02702', 4),
 ('AmBe11096', 9),
 ('AmAm09974', 9),
 ('AmAb09303', 0),
 ('AmRu13533', 2),
 ('HaRu17490', 6),
 ('KiRu26688', 2),
 ('AkKi01435', 1),
 ('HaRu17778', 0),
 ('KiIs23983', 1),
 ('AkRu02837', 2),
 ('SoRu34768', 0),
 ('AkRu05737', 2),
 ('SoIl32575', 1),
 ('SoIl32905', 9),
 ('AkRu04984', 2),
 ('HaZa21724', 3),
 ('KiRu30412', 9),
 ('HaRu17357', 9),
 ('AkRu04085', 0),
 ('AkRu05064', 0),
 ('KiRu29350', 3),
 ('SoCh32134', 9),
 ('SoRu36758', 6),
 ('SoRu37498', 3),
 ('AmAs10873', 2),
 ('AkLu02515', 3),
 ('SoMa34366', 9),
 ('AkHa00168', 9),
 ('KiZu31241', 3),
 ('AkRu07740', 2),
 ('HaRu17286', 2),
 ('AmAs10647', 7),
 ('AkRu04500', 1),
 ('SoMa34599', 0),
 ('AkRu07105', 2),
 ('AkKi01263', 2),
 ('SoBa31813', 3),
 ('AmRu12815', 2),
 ('AmRu15123', 9),
 ('KiHa23019', 1),
 ('SoRu36901', 5),
 ('AkRu04935', 3),
 ('HaRu19244', 2),
 ('KiRu26810', 3),
 ('KiRu26021', 1),
 ('SoRu39268', 9),
 ('HaRu20314', 0),
 ('HaRu20313', 5),
 ('AkRu06089', 2),
 ('SoRu37335', 2),
 ('KiRu27373', 2),
 ('SoBa31528', 3),
 ('HaRu18118', 9),
 ('AkLu01669', 2),
 ('HaRu18412', 2),
 ('AmAm09510', 9),
 ('AkRu07097', 2),
 ('AmAm09372', 9),
 ('SoIl32874', 3),
 ('HaRu19673', 6),
 ('KiRu28996', 7),
 ('SoRu36863', 0),
 ('SoRu39448', 1),
 ('SoRu36213', 0),
 ('SoRu36690', 9),
 ('AkRu06613', 2),
 ('KiRu25841', 1),
 ('AkRu06609', 3),
 ('AkRu07303', 0),
 ('AmRu13360', 9),
 ('AkHa00401', 1),
 ('HaRu19396', 1),
 ('KiRu28031', 0),
 ('SoRu36708', 3),
 ('AkRu06402', 0),
 ('AkRu05968', 1),
 ('AkRu04504', 7),
 ('AmRu13823', 9),
 ('SoCh32233', 0),
 ('AkRu04508', 1),
 ('KiZu30714', 3),
 ('SoRu37892', 0),
 ('AkRu04522', 5),
 ('AkRu03221', 1),
 ('KiRu29454', 3),
 ('AmAs10708', 9),
 ('SoBa31719', 1),
 ('HaSe21173', 3),
 ('SoBa31681', 1),
 ('AkRu03515', 9),
 ('KiRu26004', 3),
 ('SoIl32610', 9),
 ('KiMr24590', 2),
 ('AmRu15533', 3),
 ('AmRu14792', 4),
 ('KiIs23570', 2),
 ('KiRu28181', 1),
 ('AkRu04779', 0),
 ('HaDj16730', 1),
 ('SoRu36270', 0),
 ('AkLu01920', 9),
 ('AkRu03848', 3),
 ('HaSe21058', 3),
 ('KiRu27251', 3),
 ('HaRu18859', 7),
 ('SoBa31693', 2),
 ('AmRu15846', 2),
 ('AkRu07599', 7),
 ('SoIl32539', 2),
 ('KiIs24129', 1),
 ('KiRu29410', 5),
 ('AmRu13398', 2),
 ('AmRu14768', 9),
 ('HaZa21689', 1),
 ('AkLu02500', 3),
 ('KiMr24607', 2),
 ('AkLu02190', 4),
 ('KiHa23086', 3),
 ('SoRu37253', 4),
 ('AkRu06420', 3),
 ('KiIs23885', 1),
 ('SoRu35094', 9),
 ('AkRu05925', 4),
 ('KiRu26556', 2),
 ('KiRu26696', 1),
 ('AmRu14615', 3),
 ('AkRu04588', 6),
 ('SoRu34723', 4),
 ('AkRu05407', 9),
 ('KiRu26564', 9),
 ('AmRu14446', 9),
 ('HaZa21660', 1),
 ('KiRu26247', 3),
 ('AmRu13777', 9),
 ('KiRu27156', 9),
 ('HaRu19549', 1),
 ('KiHa23378', 2),
 ('AkKi01484', 3),
 ('AmPw12289', 9),
 ('KiZu30761', 4),
 ('AkRu07310', 9),
 ('AkRu07396', 2),
 ('KiMr25130', 2),
 ('AmRu13981', 3),
 ('AkRu03712', 3),
 ('HaRu20772', 1),
 ('SoRu39481', 9),
 ('SoIl32694', 9),
 ('AmPw12413', 5),
 ('AmDa11919', 3),
 ('AkRu03027', 3),
 ('AkHa00632', 3),
 ('KiAm22274', 2),
 ('AkKi01267', 9),
 ('AmAm09592', 9),
 ('AmPw12766', 3),
 ('AmRu15057', 2),
 ('HaSe21006', 3),
 ('SoRu37970', 2),
 ('AkRu08552', 3),
 ('SoRu36209', 1),
 ('AkRu03630', 7),
 ('HaRu17764', 0),
 ('SoRu37008', 3),
 ('AmAm09794', 2),
 ('KiRu29794', 3),
 ('HaDe16581', 1),
 ('KiRu26207', 9),
 ('KiAm22626', 1),
 ('AmRu15704', 2),
 ('SoRu36586', 1),
 ('AkHa00779', 3),
 ('SoRu34876', 3),
 ...]

In [22]:
%%sql

SELECT
     A.location_id AS audit_location,
	 A.true_water_source_score,
     V.location_id AS visit_location,
     V.record_id
FROM
    md_water_services.auditor_report AS A
JOIN 
   md_water_services.visits AS V
ON
    V.location_id = A.location_id;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
2698 rows affected.

[('SoRu34980', 1, 'SoRu34980', 5185),
 ('AkRu08112', 3, 'AkRu08112', 59367),
 ('AkLu02044', 0, 'AkLu02044', 37379),
 ('AkHa00421', 3, 'AkHa00421', 51627),
 ('SoRu35221', 0, 'SoRu35221', 28758),
 ('HaAm16170', 1, 'HaAm16170', 31048),
 ('AkRu04812', 3, 'AkRu04812', 1513),
 ('AkRu08304', 3, 'AkRu08304', 1218),
 ('AkRu05107', 2, 'AkRu05107', 8322),
 ('AkRu05215', 3, 'AkRu05215', 21160),
 ('HaDe16541', 2, 'HaDe16541', 13070),
 ('KiRu30351', 9, 'KiRu30351', 54220),
 ('AmAm09813', 4, 'AmAm09813', 191),
 ('SoRu37005', 0, 'SoRu37005', 51172),
 ('KiRu26067', 3, 'KiRu26067', 21010),
 ('KiRu26067', 3, 'KiRu26067', 21098),
 ('KiRu26067', 3, 'KiRu26067', 21162),
 ('KiRu26067', 3, 'KiRu26067', 21254),
 ('KiRu26067', 3, 'KiRu26067', 21281),
 ('KiRu26067', 3, 'KiRu26067', 21315),
 ('KiRu26067', 3, 'KiRu26067', 21403),
 ('KiRu26067', 3, 'KiRu26067', 21476),
 ('SoRu37100', 0, 'SoRu37100', 40276),
 ('AmDa11611', 1, 'AmDa11611', 38071),
 ('KiRu29290', 3, 'KiRu29290', 7938),
 ('KiRu29290', 3, 'KiRu29290', 8076),
 ('KiRu29290', 3, 'KiRu29290', 8108),
 ('KiRu29290', 3, 'KiRu29290', 8168),
 ('KiRu29290', 3, 'KiRu29290', 8261),
 ('KiRu29290', 3, 'KiRu29290', 8277),
 ('KiRu29290', 3, 'KiRu29290', 8360),
 ('KiRu29290', 3, 'KiRu29290', 8386),
 ('AkRu07801', 3, 'AkRu07801', 25278),
 ('AkRu07801', 3, 'AkRu07801', 25371),
 ('AkRu07801', 3, 'AkRu07801', 25405),
 ('AkRu07801', 3, 'AkRu07801', 25432),
 ('AkRu07801', 3, 'AkRu07801', 25461),
 ('AkRu07801', 3, 'AkRu07801', 25520),
 ('AkRu07801', 3, 'AkRu07801', 25667),
 ('AkRu07801', 3, 'AkRu07801', 25691),
 ('KiZu31015', 3, 'KiZu31015', 47319),
 ('KiIs24026', 2, 'KiIs24026', 2942),
 ('AkRu08480', 2, 'AkRu08480', 47118),
 ('AmBe11043', 3, 'AmBe11043', 53502),
 ('AmBe11043', 3, 'AmBe11043', 53545),
 ('AmBe11043', 3, 'AmBe11043', 53616),
 ('AmBe11043', 3, 'AmBe11043', 53737),
 ('AmBe11043', 3, 'AmBe11043', 53795),
 ('AmBe11043', 3, 'AmBe11043', 53818),
 ('AmBe11043', 3, 'AmBe11043', 53916),
 ('AmBe11043', 3, 'AmBe11043', 53939),
 ('AmRu13718', 9, 'AmRu13718', 31092),
 ('AmRu15209', 3, 'AmRu15209', 42546),
 ('AmRu15209', 3, 'AmRu15209', 42604),
 ('AmRu15209', 3, 'AmRu15209', 42632),
 ('AmRu15209', 3, 'AmRu15209', 42711),
 ('AmRu15209', 3, 'AmRu15209', 42742),
 ('AmRu15209', 3, 'AmRu15209', 42834),
 ('AmRu15209', 3, 'AmRu15209', 42918),
 ('AmRu15209', 3, 'AmRu15209', 43057),
 ('SoRu37428', 3, 'SoRu37428', 25748),
 ('SoRu37428', 3, 'SoRu37428', 25798),
 ('SoRu37428', 3, 'SoRu37428', 25854),
 ('SoRu37428', 3, 'SoRu37428', 25860),
 ('SoRu37428', 3, 'SoRu37428', 25888),
 ('SoRu37428', 3, 'SoRu37428', 25988),
 ('SoRu37428', 3, 'SoRu37428', 26070),
 ('SoRu37428', 3, 'SoRu37428', 26199),
 ('SoRu34787', 2, 'SoRu34787', 30989),
 ('AkRu03204', 3, 'AkRu03204', 36239),
 ('SoMa34137', 3, 'SoMa34137', 4657),
 ('SoRu38874', 3, 'SoRu38874', 17601),
 ('SoRu38874', 3, 'SoRu38874', 17627),
 ('SoRu38874', 3, 'SoRu38874', 17650),
 ('SoRu38874', 3, 'SoRu38874', 17661),
 ('SoRu38874', 3, 'SoRu38874', 17805),
 ('SoRu38874', 3, 'SoRu38874', 17810),
 ('SoRu38874', 3, 'SoRu38874', 17897),
 ('SoRu38874', 3, 'SoRu38874', 17987),
 ('KiMr24320', 2, 'KiMr24320', 9219),
 ('AkRu06460', 2, 'AkRu06460', 42913),
 ('KiHa22748', 9, 'KiHa22748', 43140),
 ('KiRu28673', 1, 'KiRu28673', 57339),
 ('AkHa00193', 9, 'AkHa00193', 25090),
 ('AmAs10732', 0, 'AmAs10732', 53977),
 ('KiRu27585', 3, 'KiRu27585', 2193),
 ('AkRu03541', 2, 'AkRu03541', 23766),
 ('AkRu04448', 3, 'AkRu04448', 55253),
 ('HaRu20155', 0, 'HaRu20155', 56131),
 ('AmAm09990', 5, 'AmAm09990', 3820),
 ('AmAm09990', 5, 'AmAm09990', 3830),
 ('AmAm09990', 5, 'AmAm09990', 3923),
 ('AmAm09990', 5, 'AmAm09990', 4034),
 ('AmAm09990', 5, 'AmAm09990', 4072),
 ('AmAm09990', 5, 'AmAm09990', 4150),
 ('AmAm09990', 5, 'AmAm09990', 4176),
 ('AmAm09990', 5, 'AmAm09990', 4263),
 ('KiZu31024', 0, 'KiZu31024', 53881),
 ('SoIl32392', 3, 'SoIl32392', 2825),
 ('SoIl32392', 3, 'SoIl32392', 2902),
 ('SoIl32392', 3, 'SoIl32392', 2973),
 ('SoIl32392', 3, 'SoIl32392', 3118),
 ('SoIl32392', 3, 'SoIl32392', 3181),
 ('SoIl32392', 3, 'SoIl32392', 3201),
 ('SoIl32392', 3, 'SoIl32392', 3216),
 ('SoIl32392', 3, 'SoIl32392', 3232),
 ('SoRu38699', 3, 'SoRu38699', 13821),
 ('KiAm22079', 9, 'KiAm22079', 50732),
 ('KiRu26316', 3, 'KiRu26316', 27240),
 ('KiRu26316', 3, 'KiRu26316', 27307),
 ('KiRu26316', 3, 'KiRu26316', 27418),
 ('KiRu26316', 3, 'KiRu26316', 27482),
 ('KiRu26316', 3, 'KiRu26316', 27569),
 ('KiRu26316', 3, 'KiRu26316', 27645),
 ('KiRu26316', 3, 'KiRu26316', 27670),
 ('KiRu26316', 3, 'KiRu26316', 27769),
 ('AkKi01456', 9, 'AkKi01456', 57050),
 ('AkRu08152', 2, 'AkRu08152', 43992),
 ('KiRu27444', 7, 'KiRu27444', 18928),
 ('HaRu20693', 1, 'HaRu20693', 55091),
 ('AkRu04981', 3, 'AkRu04981', 8803),
 ('KiRu28580', 1, 'KiRu28580', 14177),
 ('KiRu30008', 1, 'KiRu30008', 25914),
 ('SoMa34631', 2, 'SoMa34631', 55851),
 ('SoKo33227', 1, 'SoKo33227', 31236),
 ('AmRu14465', 3, 'AmRu14465', 23398),
 ('AmRu14465', 3, 'AmRu14465', 23526),
 ('AmRu14465', 3, 'AmRu14465', 23541),
 ('AmRu14465', 3, 'AmRu14465', 23577),
 ('AmRu14465', 3, 'AmRu14465', 23666),
 ('AmRu14465', 3, 'AmRu14465', 23748),
 ('AmRu14465', 3, 'AmRu14465', 23794),
 ('AmRu14465', 3, 'AmRu14465', 23848),
 ('AkHa00008', 3, 'AkHa00008', 57788),
 ('HaRu19826', 9, 'HaRu19826', 55626),
 ('AmDa11947', 1, 'AmDa11947', 23857),
 ('AmPw12680', 3, 'AmPw12680', 45472),
 ('AmPw12680', 3, 'AmPw12680', 45588),
 ('AmPw12680', 3, 'AmPw12680', 45653),
 ('AmPw12680', 3, 'AmPw12680', 45752),
 ('AmPw12680', 3, 'AmPw12680', 45778),
 ('AmPw12680', 3, 'AmPw12680', 45798),
 ('AmPw12680', 3, 'AmPw12680', 45809),
 ('AmPw12680', 3, 'AmPw12680', 45878),
 ('SoRu37841', 6, 'SoRu37841', 18495),
 ('KiRu27884', 1, 'KiRu27884', 33931),
 ('HaDe16514', 1, 'HaDe16514', 42469),
 ('KiMr24591', 0, 'KiMr24591', 44892),
 ('KiIs24014', 1, 'KiIs24014', 36889),
 ('AkRu07523', 3, 'AkRu07523', 22404),
 ('KiZu31170', 9, 'KiZu31170', 17950),
 ('AkRu04753', 9, 'AkRu04753', 55958),
 ('SoRu36774', 2, 'SoRu36774', 35173),
 ('SoRu36239', 2, 'SoRu36239', 43524),
 ('KiRu27776', 3, 'KiRu27776', 23770),
 ('KiRu27776', 3, 'KiRu27776', 23881),
 ('KiRu27776', 3, 'KiRu27776', 23970),
 ('KiRu27776', 3, 'KiRu27776', 24020),
 ('KiRu27776', 3, 'KiRu27776', 24065),
 ('KiRu27776', 3, 'KiRu27776', 24089),
 ('KiRu27776', 3, 'KiRu27776', 24159),
 ('KiRu27776', 3, 'KiRu27776', 24268),
 ('AkRu03164', 3, 'AkRu03164', 42866),
 ('AkRu05809', 2, 'AkRu05809', 8004),
 ('KiRu28632', 5, 'KiRu28632', 32143),
 ('KiRu28632', 5, 'KiRu28632', 32283),
 ('KiRu28632', 5, 'KiRu28632', 32304),
 ('KiRu28632', 5, 'KiRu28632', 32342),
 ('KiRu28632', 5, 'KiRu28632', 32431),
 ('KiRu28632', 5, 'KiRu28632', 32486),
 ('KiRu28632', 5, 'KiRu28632', 32577),
 ('KiRu28632', 5, 'KiRu28632', 32667),
 ('KiRu30389', 4, 'KiRu30389', 17755),
 ('AkKi01375', 3, 'AkKi01375', 40201),
 ('SoRu37530', 0, 'SoRu37530', 55624),
 ('AmBe10959', 4, 'AmBe10959', 23719),
 ('HaRu19828', 2, 'HaRu19828', 25621),
 ('SoIl32999', 2, 'SoIl32999', 32992),
 ('HaRu18571', 2, 'HaRu18571', 56000),
 ('AkRu08666', 6, 'AkRu08666', 56276),
 ('AkRu03306', 7, 'AkRu03306', 29135),
 ('AkRu08936', 3, 'AkRu08936', 132),
 ('HaSe21341', 3, 'HaSe21341', 59324),
 ('SoRu35327', 1, 'SoRu35327', 59821),
 ('AmRu14903', 9, 'AmRu14903', 54574),
 ('AmAb09101', 6, 'AmAb09101', 10635),
 ('KiAm22276', 0, 'KiAm22276', 15269),
 ('HaRu20617', 1, 'HaRu20617', 18740),
 ('KiZu31370', 3, 'KiZu31370', 36864),
 ('HaRu18217', 1, 'HaRu18217', 58386),
 ('KiRu29806', 9, 'KiRu29806', 35488),
 ('KiRu28057', 1, 'KiRu28057', 25822),
 ('AkRu06170', 3, 'AkRu06170', 16253),
 ('AkRu03380', 3, 'AkRu03380', 45718),
 ('KiRu26678', 2, 'KiRu26678', 17842),
 ('AmBe10942', 9, 'AmBe10942', 23182),
 ('KiIs23730', 3, 'KiIs23730', 59182),
 ('KiIs23730', 3, 'KiIs23730', 59319),
 ('KiIs23730', 3, 'KiIs23730', 59413),
 ('KiIs23730', 3, 'KiIs23730', 59440),
 ('KiIs23730', 3, 'KiIs23730', 59585),
 ('KiIs23730', 3, 'KiIs23730', 59600),
 ('KiIs23730', 3, 'KiIs23730', 59630),
 ('KiIs23730', 3, 'KiIs23730', 59659),
 ('KiHa23034', 3, 'KiHa23034', 39514),
 ('AkRu06495', 2, 'AkRu06495', 45924),
 ('HaRu17528', 1, 'HaRu17528', 30524),
 ('KiRu28090', 6, 'KiRu28090', 493),
 ('AmRu13729', 2, 'AmRu13729', 12421),
 ('HaRu18016', 1, 'HaRu18016', 43421),
 ('KiRu27440', 9, 'KiRu27440', 46897),
 ('HaYa21606', 3, 'HaYa21606', 54414),
 ('HaRu17207', 1, 'HaRu17207', 41291),
 ('AmAm09735', 1, 'AmAm09735', 19578),
 ('HaRu20534', 2, 'HaRu20534', 36976),
 ('SoRu38331', 3, 'SoRu38331', 13192),
 ('SoRu38331', 3, 'SoRu38331', 13282),
 ('SoRu38331', 3, 'SoRu38331', 13379),
 ('SoRu38331', 3, 'SoRu38331', 13382),
 ('SoRu38331', 3, 'SoRu38331', 13475),
 ('SoRu38331', 3, 'SoRu38331', 13496),
 ('SoRu38331', 3, 'SoRu38331', 13521),
 ('SoRu38331', 3, 'SoRu38331', 13607),
 ('AmPw12770', 3, 'AmPw12770', 57820),
 ('AkLu02096', 3, 'AkLu02096', 46932),
 ('HaRu20434', 2, 'HaRu20434', 26351),
 ('AkRu02688', 0, 'AkRu02688', 28038),
 ('AmBe11285', 9, 'AmBe11285', 30594),
 ('AmRu13720', 3, 'AmRu13720', 57704),
 ('AmRu13720', 3, 'AmRu13720', 57829),
 ('AmRu13720', 3, 'AmRu13720', 57844),
 ('AmRu13720', 3, 'AmRu13720', 57849),
 ('AmRu13720', 3, 'AmRu13720', 57870),
 ('AmRu13720', 3, 'AmRu13720', 57968),
 ('AmRu13720', 3, 'AmRu13720', 58108),
 ('AmRu13720', 3, 'AmRu13720', 58163),
 ('SoMa33819', 0, 'SoMa33819', 41990),
 ('SoRu38119', 1, 'SoRu38119', 32719),
 ('AmRu12983', 3, 'AmRu12983', 34259),
 ('SoRu35906', 5, 'SoRu35906', 23263),
 ('SoRu35906', 5, 'SoRu35906', 23333),
 ('SoRu35906', 5, 'SoRu35906', 23420),
 ('SoRu35906', 5, 'SoRu35906', 23532),
 ('SoRu35906', 5, 'SoRu35906', 23546),
 ('SoRu35906', 5, 'SoRu35906', 23587),
 ('SoRu35906', 5, 'SoRu35906', 23677),
 ('SoRu35906', 5, 'SoRu35906', 23693),
 ('KiRu27742', 3, 'KiRu27742', 20199),
 ('SoRu35991', 3, 'SoRu35991', 49145),
 ('KiRu28083', 4, 'KiRu28083', 28642),
 ('AmRu15159', 9, 'AmRu15159', 3238),
 ('HaYa21456', 2, 'HaYa21456', 31258),
 ('HaRu18734', 2, 'HaRu18734', 9967),
 ('SoRu35970', 3, 'SoRu35970', 49787),
 ('AmAs10285', 3, 'AmAs10285', 35054),
 ('AmAs10285', 3, 'AmAs10285', 35109),
 ('AmAs10285', 3, 'AmAs10285', 35135),
 ('AmAs10285', 3, 'AmAs10285', 35257),
 ('AmAs10285', 3, 'AmAs10285', 35277),
 ('AmAs10285', 3, 'AmAs10285', 35454),
 ('AmAs10285', 3, 'AmAs10285', 35462),
 ('AmAs10285', 3, 'AmAs10285', 35578),
 ('AmRu15556', 9, 'AmRu15556', 15461),
 ('KiZu31223', 3, 'KiZu31223', 45820),
 ('KiZu31223', 3, 'KiZu31223', 45947),
 ('KiZu31223', 3, 'KiZu31223', 46006),
 ('KiZu31223', 3, 'KiZu31223', 46113),
 ('KiZu31223', 3, 'KiZu31223', 46153),
 ('KiZu31223', 3, 'KiZu31223', 46222),
 ('KiZu31223', 3, 'KiZu31223', 46246),
 ('KiZu31223', 3, 'KiZu31223', 46251),
 ('SoRu38546', 9, 'SoRu38546', 31987),
 ('AmPw12293', 6, 'AmPw12293', 43323),
 ('SoRu39488', 3, 'SoRu39488', 778),
 ('SoRu39488', 3, 'SoRu39488', 889),
 ('SoRu39488', 3, 'SoRu39488', 902),
 ('SoRu39488', 3, 'SoRu39488', 927),
 ('SoRu39488', 3, 'SoRu39488', 984),
 ('SoRu39488', 3, 'SoRu39488', 1043),
 ('SoRu39488', 3, 'SoRu39488', 1178),
 ('SoRu39488', 3, 'SoRu39488', 1199),
 ('SoRu39408', 5, 'SoRu39408', 9997),
 ('SoRu39408', 5, 'SoRu39408', 10080),
 ('SoRu39408', 5, 'SoRu39408', 10156),
 ('SoRu39408', 5, 'SoRu39408', 10194),
 ('SoRu39408', 5, 'SoRu39408', 10197),
 ('SoRu39408', 5, 'SoRu39408', 10298),
 ('SoRu39408', 5, 'SoRu39408', 10444),
 ('SoRu39408', 5, 'SoRu39408', 10496),
 ('HaRu17750', 2, 'HaRu17750', 55863),
 ('AmAm09607', 9, 'AmAm09607', 55067),
 ('KiRu30604', 0, 'KiRu30604', 38650),
 ('KiZu30905', 9, 'KiZu30905', 38879),
 ('SoRu39374', 9, 'SoRu39374', 12919),
 ('AkHa00314', 9, 'AkHa00314', 29407),
 ('SoRu37406', 2, 'SoRu37406', 36882),
 ('AkRu05212', 9, 'AkRu05212', 41421),
 ('SoIl32294', 0, 'SoIl32294', 58139),
 ('AmBe11313', 0, 'AmBe11313', 12271),
 ('SoRu35426', 3, 'SoRu35426', 12319),
 ('AkHa00073', 3, 'AkHa00073', 13554),
 ('SoRu35899', 9, 'SoRu35899', 10054),
 ('KiRu26664', 2, 'KiRu26664', 30561),
 ('SoRu36580', 3, 'SoRu36580', 15465),
 ('SoRu36580', 3, 'SoRu36580', 15591),
 ('SoRu36580', 3, 'SoRu36580', 15594),
 ('SoRu36580', 3, 'SoRu36580', 15682),
 ('SoRu36580', 3, 'SoRu36580', 15764),
 ('SoRu36580', 3, 'SoRu36580', 15815),
 ('SoRu36580', 3, 'SoRu36580', 15846),
 ('SoRu36580', 3, 'SoRu36580', 15996),
 ('KiRu26598', 9, 'KiRu26598', 28874),
 ('AkLu02432', 2, 'AkLu02432', 56526),
 ('HaRu19287', 5, 'HaRu19287', 54666),
 ('HaRu19287', 5, 'HaRu19287', 54686),
 ('HaRu19287', 5, 'HaRu19287', 54700),
 ('HaRu19287', 5, 'HaRu19287', 54724),
 ('HaRu19287', 5, 'HaRu19287', 54884),
 ('HaRu19287', 5, 'HaRu19287', 54897),
 ('HaRu19287', 5, 'HaRu19287', 54983),
 ('HaRu19287', 5, 'HaRu19287', 55053),
 ('SoRu38915', 1, 'SoRu38915', 26133),
 ('KiRu26032', 0, 'KiRu26032', 12342),
 ('KiRu25619', 3, 'KiRu25619', 48832),
 ('KiIs23853', 2, 'KiIs23853', 55796),
 ('AkHa00172', 2, 'AkHa00172', 41191),
 ('KiRu27927', 3, 'KiRu27927', 33105),
 ('KiRu28045', 2, 'KiRu28045', 16862),
 ('KiRu29614', 1, 'KiRu29614', 51573),
 ('KiRu25484', 1, 'KiRu25484', 20447),
 ('AkRu04989', 1, 'AkRu04989', 34369),
 ('AkKi01455', 3, 'AkKi01455', 16750),
 ('AkKi01455', 3, 'AkKi01455', 16781),
 ('AkKi01455', 3, 'AkKi01455', 16787),
 ('AkKi01455', 3, 'AkKi01455', 16887),
 ('AkKi01455', 3, 'AkKi01455', 16967),
 ('AkKi01455', 3, 'AkKi01455', 17025),
 ('AkKi01455', 3, 'AkKi01455', 17124),
 ('AkKi01455', 3, 'AkKi01455', 17139),
 ('SoIl33047', 2, 'SoIl33047', 45984),
 ('SoCh32025', 0, 'SoCh32025', 14252),
 ('KiRu28089', 0, 'KiRu28089', 9134),
 ('AkRu07622', 2, 'AkRu07622', 18841),
 ('KiRu29909', 1, 'KiRu29909', 28639),
 ('AmBe11266', 9, 'AmBe11266', 6032),
 ('AkRu03475', 1, 'AkRu03475', 33630),
 ('KiRu26934', 2, 'KiRu26934', 44733),
 ('SoRu35691', 5, 'SoRu35691', 13341),
 ('SoRu35691', 5, 'SoRu35691', 13440),
 ('SoRu35691', 5, 'SoRu35691', 13482),
 ('SoRu35691', 5, 'SoRu35691', 13504),
 ('SoRu35691', 5, 'SoRu35691', 13549),
 ('SoRu35691', 5, 'SoRu35691', 13591),
 ('SoRu35691', 5, 'SoRu35691', 13742),
 ('SoRu35691', 5, 'SoRu35691', 13810),
 ('SoMa34148', 2, 'SoMa34148', 50300),
 ('AmRu15860', 1, 'AmRu15860', 46070),
 ('SoRu38125', 5, 'SoRu38125', 26141),
 ('SoRu38125', 5, 'SoRu38125', 26252),
 ('SoRu38125', 5, 'SoRu38125', 26300),
 ('SoRu38125', 5, 'SoRu38125', 26322),
 ('SoRu38125', 5, 'SoRu38125', 26358),
 ('SoRu38125', 5, 'SoRu38125', 26410),
 ('SoRu38125', 5, 'SoRu38125', 26502),
 ('SoRu38125', 5, 'SoRu38125', 26634),
 ('AkLu02637', 9, 'AkLu02637', 13812),
 ('KiIs24083', 2, 'KiIs24083', 28404),
 ('SoRu35824', 1, 'SoRu35824', 28362),
 ('KiRu27806', 0, 'KiRu27806', 42076),
 ('AkRu03182', 3, 'AkRu03182', 13651),
 ('AkHa00088', 1, 'AkHa00088', 12774),
 ('SoRu36828', 2, 'SoRu36828', 5668),
 ('AkLu02438', 9, 'AkLu02438', 24429),
 ('SoRu38250', 6, 'SoRu38250', 21140),
 ('AkHa00613', 3, 'AkHa00613', 20924),
 ('KiMr25005', 0, 'KiMr25005', 58102),
 ('AkRu04428', 3, 'AkRu04428', 9203),
 ('SoRu35103', 5, 'SoRu35103', 44051),
 ('SoRu35103', 5, 'SoRu35103', 44145),
 ('SoRu35103', 5, 'SoRu35103', 44178),
 ('SoRu35103', 5, 'SoRu35103', 44237),
 ('SoRu35103', 5, 'SoRu35103', 44338),
 ('SoRu35103', 5, 'SoRu35103', 44370),
 ('SoRu35103', 5, 'SoRu35103', 44394),
 ('SoRu35103', 5, 'SoRu35103', 44522),
 ('SoRu36975', 0, 'SoRu36975', 26255),
 ('AkHa00662', 2, 'AkHa00662', 52082),
 ('SoCh31985', 3, 'SoCh31985', 37231),
 ('AmAm09631', 9, 'AmAm09631', 14211),
 ('SoRu37129', 0, 'SoRu37129', 31642),
 ('SoRu38416', 3, 'SoRu38416', 49607),
 ('SoRu38416', 3, 'SoRu38416', 49625),
 ('SoRu38416', 3, 'SoRu38416', 49798),
 ('SoRu38416', 3, 'SoRu38416', 49817),
 ('SoRu38416', 3, 'SoRu38416', 49850),
 ('SoRu38416', 3, 'SoRu38416', 49869),
 ('SoRu38416', 3, 'SoRu38416', 49977),
 ('SoRu38416', 3, 'SoRu38416', 50037),
 ('AkRu02670', 2, 'AkRu02670', 8346),
 ('AkHa00487', 3, 'AkHa00487', 14442),
 ('SoRu36186', 0, 'SoRu36186', 16286),
 ('AkRu03649', 2, 'AkRu03649', 4101),
 ('KiRu30343', 2, 'KiRu30343', 51075),
 ('AmRu13668', 9, 'AmRu13668', 10586),
 ('SoMa34044', 0, 'SoMa34044', 20902),
 ('AmRu14531', 9, 'AmRu14531', 13172),
 ('SoRu37317', 2, 'SoRu37317', 50347),
 ('KiIs23613', 6, 'KiIs23613', 3093),
 ('SoRu39288', 0, 'SoRu39288', 13409),
 ('AkRu07820', 3, 'AkRu07820', 34009),
 ('AkRu07774', 3, 'AkRu07774', 24774),
 ('SoBa31691', 0, 'SoBa31691', 3267),
 ('SoRu36385', 2, 'SoRu36385', 54896),
 ('KiIs24054', 9, 'KiIs24054', 21978),
 ('KiRu29129', 1, 'KiRu29129', 32520),
 ('KiHa23042', 1, 'KiHa23042', 54900),
 ('AkHa00459', 1, 'AkHa00459', 39863),
 ('SoBa31659', 3, 'SoBa31659', 17354),
 ('KiRu30394', 4, 'KiRu30394', 6624),
 ('SoKo33111', 1, 'SoKo33111', 19195),
 ('AkRu03429', 3, 'AkRu03429', 17142),
 ('KiRu26860', 0, 'KiRu26860', 24912),
 ('KiAm22303', 9, 'KiAm22303', 56325),
 ('HaRu18493', 3, 'HaRu18493', 25264),
 ('HaRu18608', 1, 'HaRu18608', 4779),
 ('SoRu35964', 2, 'SoRu35964', 58643),
 ('KiMr24872', 2, 'KiMr24872', 47577),
 ('KiAm22458', 2, 'KiAm22458', 672),
 ('AkRu05603', 3, 'AkRu05603', 54483),
 ('HaRu20851', 9, 'HaRu20851', 56353),
 ('KiRu25343', 1, 'KiRu25343', 41757),
 ('SoRu36816', 3, 'SoRu36816', 57218),
 ('HaRu20840', 3, 'HaRu20840', 43798),
 ('HaRu20840', 3, 'HaRu20840', 43873),
 ('HaRu20840', 3, 'HaRu20840', 43894),
 ('HaRu20840', 3, 'HaRu20840', 43914),
 ('HaRu20840', 3, 'HaRu20840', 44065),
 ('HaRu20840', 3, 'HaRu20840', 44121),
 ('HaRu20840', 3, 'HaRu20840', 44189),
 ('HaRu20840', 3, 'HaRu20840', 44278),
 ('SoRu38966', 5, 'SoRu38966', 3240),
 ('SoRu37494', 9, 'SoRu37494', 17009),
 ('HaRu19176', 1, 'HaRu19176', 25331),
 ('AmBe11175', 3, 'AmBe11175', 22982),
 ('AmBe11175', 3, 'AmBe11175', 23048),
 ('AmBe11175', 3, 'AmBe11175', 23088),
 ('AmBe11175', 3, 'AmBe11175', 23094),
 ('AmBe11175', 3, 'AmBe11175', 23115),
 ('AmBe11175', 3, 'AmBe11175', 23200),
 ('AmBe11175', 3, 'AmBe11175', 23287),
 ('AmBe11175', 3, 'AmBe11175', 23453),
 ('HaDe16360', 1, 'HaDe16360', 19732),
 ('AmBe11054', 9, 'AmBe11054', 8225),
 ('AkRu08460', 2, 'AkRu08460', 59776),
 ('SoKo33124', 3, 'SoKo33124', 2006),
 ('SoKo33124', 3, 'SoKo33124', 2107),
 ('SoKo33124', 3, 'SoKo33124', 2220),
 ('SoKo33124', 3, 'SoKo33124', 2278),
 ('SoKo33124', 3, 'SoKo33124', 2304),
 ('SoKo33124', 3, 'SoKo33124', 2330),
 ('SoKo33124', 3, 'SoKo33124', 2373),
 ('SoKo33124', 3, 'SoKo33124', 2458),
 ('AkKi01211', 3, 'AkKi01211', 16824),
 ('SoIl32445', 2, 'SoIl32445', 25386),
 ('AmRu13532', 9, 'AmRu13532', 39886),
 ('SoRu36142', 1, 'SoRu36142', 7542),
 ('AkRu05020', 3, 'AkRu05020', 4291),
 ('HaRu18730', 1, 'HaRu18730', 34773),
 ('KiRu25527', 2, 'KiRu25527', 30088),
 ('AkRu05442', 3, 'AkRu05442', 59724),
 ('AkRu05207', 3, 'AkRu05207', 53713),
 ('AkRu05207', 3, 'AkRu05207', 53800),
 ('AkRu05207', 3, 'AkRu05207', 53824),
 ('AkRu05207', 3, 'AkRu05207', 53914),
 ('AkRu05207', 3, 'AkRu05207', 53928),
 ('AkRu05207', 3, 'AkRu05207', 54036),
 ('AkRu05207', 3, 'AkRu05207', 54157),
 ('AkRu05207', 3, 'AkRu05207', 54160),
 ('AmAm09844', 9, 'AmAm09844', 39550),
 ('AkRu04217', 3, 'AkRu04217', 18145),
 ('SoRu38733', 5, 'SoRu38733', 16689),
 ('SoBa31655', 9, 'SoBa31655', 5710),
 ('SoRu37392', 4, 'SoRu37392', 17821),
 ('SoRu37392', 4, 'SoRu37392', 17894),
 ('SoRu37392', 4, 'SoRu37392', 18045),
 ('SoRu37392', 4, 'SoRu37392', 18088),
 ('SoRu37392', 4, 'SoRu37392', 18116),
 ('SoRu37392', 4, 'SoRu37392', 18215),
 ('SoRu37392', 4, 'SoRu37392', 18263),
 ('SoRu37392', 4, 'SoRu37392', 18383),
 ('AkKi01238', 3, 'AkKi01238', 15839),
 ('AmRu14527', 3, 'AmRu14527', 36952),
 ('KiRu26502', 3, 'KiRu26502', 9396),
 ('AkRu06339', 0, 'AkRu06339', 28338),
 ('SoRu37920', 0, 'SoRu37920', 42676),
 ('AkRu02682', 2, 'AkRu02682', 26484),
 ('AmBe10969', 3, 'AmBe10969', 39852),
 ('AmBe10969', 3, 'AmBe10969', 39963),
 ('AmBe10969', 3, 'AmBe10969', 40094),
 ('AmBe10969', 3, 'AmBe10969', 40134),
 ('AmBe10969', 3, 'AmBe10969', 40214),
 ('AmBe10969', 3, 'AmBe10969', 40307),
 ('AmBe10969', 3, 'AmBe10969', 40313),
 ('AmBe10969', 3, 'AmBe10969', 40414),
 ('AkRu08755', 3, 'AkRu08755', 19813),
 ('KiRu30051', 2, 'KiRu30051', 13174),
 ('HaRu19054', 2, 'HaRu19054', 314),
 ('HaRu17182', 1, 'HaRu17182', 26851),
 ('AmBe11275', 3, 'AmBe11275', 26263),
 ('AmBe11275', 3, 'AmBe11275', 26302),
 ('AmBe11275', 3, 'AmBe11275', 26312),
 ('AmBe11275', 3, 'AmBe11275', 26386),
 ('AmBe11275', 3, 'AmBe11275', 26491),
 ('AmBe11275', 3, 'AmBe11275', 26575),

In [23]:
%%sql
-- Now that we have the record_id for each location, 
-- We our next step is to retrieve the corresponding scores from the water_quality table. 
-- are particularly interested in the subjective_quality_score. To do this,
-- we'll JOIN the visits table and the water_quality table, using the
-- record_id as the connecting key.   PAGE(9)

SELECT
     V.location_id AS audit_location,
	 A.true_water_source_score,
     WAT_Q.record_id AS visit_location,
     V.record_id,
     WAT_Q.subjective_quality_score
FROM
    md_water_services.visits AS V
JOIN 
   md_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	md_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id

 * mysql+pymysql://root:***@localhost:3306/md_water_services
2698 rows affected.

[('SoRu34980', 1, 5185, 5185, 1),
 ('AkRu08112', 3, 59367, 59367, 3),
 ('AkLu02044', 0, 37379, 37379, 0),
 ('AkHa00421', 3, 51627, 51627, 3),
 ('SoRu35221', 0, 28758, 28758, 0),
 ('HaAm16170', 1, 31048, 31048, 1),
 ('AkRu04812', 3, 1513, 1513, 3),
 ('AkRu08304', 3, 1218, 1218, 3),
 ('AkRu05107', 2, 8322, 8322, 2),
 ('AkRu05215', 3, 21160, 21160, 10),
 ('HaDe16541', 2, 13070, 13070, 2),
 ('KiRu30351', 9, 54220, 54220, 9),
 ('AmAm09813', 4, 191, 191, 4),
 ('SoRu37005', 0, 51172, 51172, 0),
 ('KiRu26067', 3, 21010, 21010, 3),
 ('KiRu26067', 3, 21098, 21098, 3),
 ('KiRu26067', 3, 21162, 21162, 3),
 ('KiRu26067', 3, 21254, 21254, 3),
 ('KiRu26067', 3, 21281, 21281, 3),
 ('KiRu26067', 3, 21315, 21315, 3),
 ('KiRu26067', 3, 21403, 21403, 3),
 ('KiRu26067', 3, 21476, 21476, 3),
 ('SoRu37100', 0, 40276, 40276, 0),
 ('AmDa11611', 1, 38071, 38071, 1),
 ('KiRu29290', 3, 7938, 7938, 10),
 ('KiRu29290', 3, 8076, 8076, 10),
 ('KiRu29290', 3, 8108, 8108, 10),
 ('KiRu29290', 3, 8168, 8168, 10),
 ('KiRu29290', 3, 8261, 8261, 10),
 ('KiRu29290', 3, 8277, 8277, 10),
 ('KiRu29290', 3, 8360, 8360, 10),
 ('KiRu29290', 3, 8386, 8386, 10),
 ('AkRu07801', 3, 25278, 25278, 3),
 ('AkRu07801', 3, 25371, 25371, 3),
 ('AkRu07801', 3, 25405, 25405, 3),
 ('AkRu07801', 3, 25432, 25432, 3),
 ('AkRu07801', 3, 25461, 25461, 3),
 ('AkRu07801', 3, 25520, 25520, 3),
 ('AkRu07801', 3, 25667, 25667, 3),
 ('AkRu07801', 3, 25691, 25691, 3),
 ('KiZu31015', 3, 47319, 47319, 3),
 ('KiIs24026', 2, 2942, 2942, 2),
 ('AkRu08480', 2, 47118, 47118, 2),
 ('AmBe11043', 3, 53502, 53502, 3),
 ('AmBe11043', 3, 53545, 53545, 3),
 ('AmBe11043', 3, 53616, 53616, 3),
 ('AmBe11043', 3, 53737, 53737, 3),
 ('AmBe11043', 3, 53795, 53795, 3),
 ('AmBe11043', 3, 53818, 53818, 3),
 ('AmBe11043', 3, 53916, 53916, 3),
 ('AmBe11043', 3, 53939, 53939, 3),
 ('AmRu13718', 9, 31092, 31092, 9),
 ('AmRu15209', 3, 42546, 42546, 3),
 ('AmRu15209', 3, 42604, 42604, 3),
 ('AmRu15209', 3, 42632, 42632, 3),
 ('AmRu15209', 3, 42711, 42711, 3),
 ('AmRu15209', 3, 42742, 42742, 3),
 ('AmRu15209', 3, 42834, 42834, 3),
 ('AmRu15209', 3, 42918, 42918, 3),
 ('AmRu15209', 3, 43057, 43057, 3),
 ('SoRu37428', 3, 25748, 25748, 3),
 ('SoRu37428', 3, 25798, 25798, 3),
 ('SoRu37428', 3, 25854, 25854, 3),
 ('SoRu37428', 3, 25860, 25860, 3),
 ('SoRu37428', 3, 25888, 25888, 3),
 ('SoRu37428', 3, 25988, 25988, 3),
 ('SoRu37428', 3, 26070, 26070, 3),
 ('SoRu37428', 3, 26199, 26199, 3),
 ('SoRu34787', 2, 30989, 30989, 2),
 ('AkRu03204', 3, 36239, 36239, 3),
 ('SoMa34137', 3, 4657, 4657, 3),
 ('SoRu38874', 3, 17601, 17601, 3),
 ('SoRu38874', 3, 17627, 17627, 3),
 ('SoRu38874', 3, 17650, 17650, 3),
 ('SoRu38874', 3, 17661, 17661, 3),
 ('SoRu38874', 3, 17805, 17805, 3),
 ('SoRu38874', 3, 17810, 17810, 3),
 ('SoRu38874', 3, 17897, 17897, 3),
 ('SoRu38874', 3, 17987, 17987, 3),
 ('KiMr24320', 2, 9219, 9219, 2),
 ('AkRu06460', 2, 42913, 42913, 2),
 ('KiHa22748', 9, 43140, 43140, 10),
 ('KiRu28673', 1, 57339, 57339, 1),
 ('AkHa00193', 9, 25090, 25090, 9),
 ('AmAs10732', 0, 53977, 53977, 0),
 ('KiRu27585', 3, 2193, 2193, 3),
 ('AkRu03541', 2, 23766, 23766, 2),
 ('AkRu04448', 3, 55253, 55253, 3),
 ('HaRu20155', 0, 56131, 56131, 0),
 ('AmAm09990', 5, 3820, 3820, 5),
 ('AmAm09990', 5, 3830, 3830, 5),
 ('AmAm09990', 5, 3923, 3923, 5),
 ('AmAm09990', 5, 4034, 4034, 5),
 ('AmAm09990', 5, 4072, 4072, 5),
 ('AmAm09990', 5, 4150, 4150, 5),
 ('AmAm09990', 5, 4176, 4176, 5),
 ('AmAm09990', 5, 4263, 4263, 5),
 ('KiZu31024', 0, 53881, 53881, 0),
 ('SoIl32392', 3, 2825, 2825, 3),
 ('SoIl32392', 3, 2902, 2902, 3),
 ('SoIl32392', 3, 2973, 2973, 3),
 ('SoIl32392', 3, 3118, 3118, 3),
 ('SoIl32392', 3, 3181, 3181, 3),
 ('SoIl32392', 3, 3201, 3201, 3),
 ('SoIl32392', 3, 3216, 3216, 3),
 ('SoIl32392', 3, 3232, 3232, 3),
 ('SoRu38699', 3, 13821, 13821, 3),
 ('KiAm22079', 9, 50732, 50732, 9),
 ('KiRu26316', 3, 27240, 27240, 3),
 ('KiRu26316', 3, 27307, 27307, 3),
 ('KiRu26316', 3, 27418, 27418, 3),
 ('KiRu26316', 3, 27482, 27482, 3),
 ('KiRu26316', 3, 27569, 27569, 3),
 ('KiRu26316', 3, 27645, 27645, 3),
 ('KiRu26316', 3, 27670, 27670, 3),
 ('KiRu26316', 3, 27769, 27769, 3),
 ('AkKi01456', 9, 57050, 57050, 9),
 ('AkRu08152', 2, 43992, 43992, 2),
 ('KiRu27444', 7, 18928, 18928, 7),
 ('HaRu20693', 1, 55091, 55091, 1),
 ('AkRu04981', 3, 8803, 8803, 3),
 ('KiRu28580', 1, 14177, 14177, 1),
 ('KiRu30008', 1, 25914, 25914, 1),
 ('SoMa34631', 2, 55851, 55851, 2),
 ('SoKo33227', 1, 31236, 31236, 1),
 ('AmRu14465', 3, 23398, 23398, 3),
 ('AmRu14465', 3, 23526, 23526, 3),
 ('AmRu14465', 3, 23541, 23541, 3),
 ('AmRu14465', 3, 23577, 23577, 3),
 ('AmRu14465', 3, 23666, 23666, 3),
 ('AmRu14465', 3, 23748, 23748, 3),
 ('AmRu14465', 3, 23794, 23794, 3),
 ('AmRu14465', 3, 23848, 23848, 3),
 ('AkHa00008', 3, 57788, 57788, 3),
 ('HaRu19826', 9, 55626, 55626, 9),
 ('AmDa11947', 1, 23857, 23857, 1),
 ('AmPw12680', 3, 45472, 45472, 3),
 ('AmPw12680', 3, 45588, 45588, 3),
 ('AmPw12680', 3, 45653, 45653, 3),
 ('AmPw12680', 3, 45752, 45752, 3),
 ('AmPw12680', 3, 45778, 45778, 3),
 ('AmPw12680', 3, 45798, 45798, 3),
 ('AmPw12680', 3, 45809, 45809, 3),
 ('AmPw12680', 3, 45878, 45878, 3),
 ('SoRu37841', 6, 18495, 18495, 10),
 ('KiRu27884', 1, 33931, 33931, 10),
 ('HaDe16514', 1, 42469, 42469, 1),
 ('KiMr24591', 0, 44892, 44892, 0),
 ('KiIs24014', 1, 36889, 36889, 1),
 ('AkRu07523', 3, 22404, 22404, 3),
 ('KiZu31170', 9, 17950, 17950, 10),
 ('AkRu04753', 9, 55958, 55958, 9),
 ('SoRu36774', 2, 35173, 35173, 2),
 ('SoRu36239', 2, 43524, 43524, 2),
 ('KiRu27776', 3, 23770, 23770, 3),
 ('KiRu27776', 3, 23881, 23881, 3),
 ('KiRu27776', 3, 23970, 23970, 3),
 ('KiRu27776', 3, 24020, 24020, 3),
 ('KiRu27776', 3, 24065, 24065, 3),
 ('KiRu27776', 3, 24089, 24089, 3),
 ('KiRu27776', 3, 24159, 24159, 3),
 ('KiRu27776', 3, 24268, 24268, 3),
 ('AkRu03164', 3, 42866, 42866, 3),
 ('AkRu05809', 2, 8004, 8004, 2),
 ('KiRu28632', 5, 32143, 32143, 5),
 ('KiRu28632', 5, 32283, 32283, 5),
 ('KiRu28632', 5, 32304, 32304, 5),
 ('KiRu28632', 5, 32342, 32342, 5),
 ('KiRu28632', 5, 32431, 32431, 5),
 ('KiRu28632', 5, 32486, 32486, 5),
 ('KiRu28632', 5, 32577, 32577, 5),
 ('KiRu28632', 5, 32667, 32667, 5),
 ('KiRu30389', 4, 17755, 17755, 4),
 ('AkKi01375', 3, 40201, 40201, 3),
 ('SoRu37530', 0, 55624, 55624, 0),
 ('AmBe10959', 4, 23719, 23719, 4),
 ('HaRu19828', 2, 25621, 25621, 2),
 ('SoIl32999', 2, 32992, 32992, 2),
 ('HaRu18571', 2, 56000, 56000, 2),
 ('AkRu08666', 6, 56276, 56276, 6),
 ('AkRu03306', 7, 29135, 29135, 7),
 ('AkRu08936', 3, 132, 132, 3),
 ('HaSe21341', 3, 59324, 59324, 3),
 ('SoRu35327', 1, 59821, 59821, 1),
 ('AmRu14903', 9, 54574, 54574, 9),
 ('AmAb09101', 6, 10635, 10635, 6),
 ('KiAm22276', 0, 15269, 15269, 0),
 ('HaRu20617', 1, 18740, 18740, 1),
 ('KiZu31370', 3, 36864, 36864, 10),
 ('HaRu18217', 1, 58386, 58386, 1),
 ('KiRu29806', 9, 35488, 35488, 9),
 ('KiRu28057', 1, 25822, 25822, 1),
 ('AkRu06170', 3, 16253, 16253, 3),
 ('AkRu03380', 3, 45718, 45718, 3),
 ('KiRu26678', 2, 17842, 17842, 2),
 ('AmBe10942', 9, 23182, 23182, 9),
 ('KiIs23730', 3, 59182, 59182, 3),
 ('KiIs23730', 3, 59319, 59319, 3),
 ('KiIs23730', 3, 59413, 59413, 3),
 ('KiIs23730', 3, 59440, 59440, 3),
 ('KiIs23730', 3, 59585, 59585, 3),
 ('KiIs23730', 3, 59600, 59600, 3),
 ('KiIs23730', 3, 59630, 59630, 3),
 ('KiIs23730', 3, 59659, 59659, 3),
 ('KiHa23034', 3, 39514, 39514, 3),
 ('AkRu06495', 2, 45924, 45924, 10),
 ('HaRu17528', 1, 30524, 30524, 10),
 ('KiRu28090', 6, 493, 493, 6),
 ('AmRu13729', 2, 12421, 12421, 2),
 ('HaRu18016', 1, 43421, 43421, 1),
 ('KiRu27440', 9, 46897, 46897, 9),
 ('HaYa21606', 3, 54414, 54414, 3),
 ('HaRu17207', 1, 41291, 41291, 1),
 ('AmAm09735', 1, 19578, 19578, 1),
 ('HaRu20534', 2, 36976, 36976, 2),
 ('SoRu38331', 3, 13192, 13192, 10),
 ('SoRu38331', 3, 13282, 13282, 10),
 ('SoRu38331', 3, 13379, 13379, 10),
 ('SoRu38331', 3, 13382, 13382, 10),
 ('SoRu38331', 3, 13475, 13475, 10),
 ('SoRu38331', 3, 13496, 13496, 10),
 ('SoRu38331', 3, 13521, 13521, 10),
 ('SoRu38331', 3, 13607, 13607, 10),
 ('AmPw12770', 3, 57820, 57820, 3),
 ('AkLu02096', 3, 46932, 46932, 3),
 ('HaRu20434', 2, 26351, 26351, 2),
 ('AkRu02688', 0, 28038, 28038, 0),
 ('AmBe11285', 9, 30594, 30594, 9),
 ('AmRu13720', 3, 57704, 57704, 3),
 ('AmRu13720', 3, 57829, 57829, 3),
 ('AmRu13720', 3, 57844, 57844, 3),
 ('AmRu13720', 3, 57849, 57849, 3),
 ('AmRu13720', 3, 57870, 57870, 3),
 ('AmRu13720', 3, 57968, 57968, 3),
 ('AmRu13720', 3, 58108, 58108, 3),
 ('AmRu13720', 3, 58163, 58163, 3),
 ('SoMa33819', 0, 41990, 41990, 0),
 ('SoRu38119', 1, 32719, 32719, 1),
 ('AmRu12983', 3, 34259, 34259, 3),
 ('SoRu35906', 5, 23263, 23263, 5),
 ('SoRu35906', 5, 23333, 23333, 5),
 ('SoRu35906', 5, 23420, 23420, 5),
 ('SoRu35906', 5, 23532, 23532, 5),
 ('SoRu35906', 5, 23546, 23546, 5),
 ('SoRu35906', 5, 23587, 23587, 5),
 ('SoRu35906', 5, 23677, 23677, 5),
 ('SoRu35906', 5, 23693, 23693, 5),
 ('KiRu27742', 3, 20199, 20199, 3),
 ('SoRu35991', 3, 49145, 49145, 3),
 ('KiRu28083', 4, 28642, 28642, 4),
 ('AmRu15159', 9, 3238, 3238, 9),
 ('HaYa21456', 2, 31258, 31258, 2),
 ('HaRu18734', 2, 9967, 9967, 2),
 ('SoRu35970', 3, 49787, 49787, 3),
 ('AmAs10285', 3, 35054, 35054, 3),
 ('AmAs10285', 3, 35109, 35109, 3),
 ('AmAs10285', 3, 35135, 35135, 3),
 ('AmAs10285', 3, 35257, 35257, 3),
 ('AmAs10285', 3, 35277, 35277, 3),
 ('AmAs10285', 3, 35454, 35454, 3),
 ('AmAs10285', 3, 35462, 35462, 3),
 ('AmAs10285', 3, 35578, 35578, 3),
 ('AmRu15556', 9, 15461, 15461, 10),
 ('KiZu31223', 3, 45820, 45820, 3),
 ('KiZu31223', 3, 45947, 45947, 3),
 ('KiZu31223', 3, 46006, 46006, 3),
 ('KiZu31223', 3, 46113, 46113, 3),
 ('KiZu31223', 3, 46153, 46153, 3),
 ('KiZu31223', 3, 46222, 46222, 3),
 ('KiZu31223', 3, 46246, 46246, 3),
 ('KiZu31223', 3, 46251, 46251, 3),
 ('SoRu38546', 9, 31987, 31987, 9),
 ('AmPw12293', 6, 43323, 43323, 6),
 ('SoRu39488', 3, 778, 778, 3),
 ('SoRu39488', 3, 889, 889, 3),
 ('SoRu39488', 3, 902, 902, 3),
 ('SoRu39488', 3, 927, 927, 3),
 ('SoRu39488', 3, 984, 984, 3),
 ('SoRu39488', 3, 1043, 1043, 3),
 ('SoRu39488', 3, 1178, 1178, 3),
 ('SoRu39488', 3, 1199, 1199, 3),
 ('SoRu39408', 5, 9997, 9997, 5),
 ('SoRu39408', 5, 10080, 10080, 5),
 ('SoRu39408', 5, 10156, 10156, 5),
 ('SoRu39408', 5, 10194, 10194, 5),
 ('SoRu39408', 5, 10197, 10197, 5),
 ('SoRu39408', 5, 10298, 10298, 5),
 ('SoRu39408', 5, 10444, 10444, 5),
 ('SoRu39408', 5, 10496, 10496, 5),
 ('HaRu17750', 2, 55863, 55863, 2),
 ('AmAm09607', 9, 55067, 55067, 10),
 ('KiRu30604', 0, 38650, 38650, 0),
 ('KiZu30905', 9, 38879, 38879, 9),
 ('SoRu39374', 9, 12919, 12919, 9),
 ('AkHa00314', 9, 29407, 29407, 10),
 ('SoRu37406', 2, 36882, 36882, 2),
 ('AkRu05212', 9, 41421, 41421, 9),
 ('SoIl32294', 0, 58139, 58139, 0),
 ('AmBe11313', 0, 12271, 12271, 0),
 ('SoRu35426', 3, 12319, 12319, 3),
 ('AkHa00073', 3, 13554, 13554, 3),
 ('SoRu35899', 9, 10054, 10054, 9),
 ('KiRu26664', 2, 30561, 30561, 2),
 ('SoRu36580', 3, 15465, 15465, 3),
 ('SoRu36580', 3, 15591, 15591, 3),
 ('SoRu36580', 3, 15594, 15594, 3),
 ('SoRu36580', 3, 15682, 15682, 3),
 ('SoRu36580', 3, 15764, 15764, 3),
 ('SoRu36580', 3, 15815, 15815, 3),
 ('SoRu36580', 3, 15846, 15846, 3),
 ('SoRu36580', 3, 15996, 15996, 3),
 ('KiRu26598', 9, 28874, 28874, 10),
 ('AkLu02432', 2, 56526, 56526, 2),
 ('HaRu19287', 5, 54666, 54666, 5),
 ('HaRu19287', 5, 54686, 54686, 5),
 ('HaRu19287', 5, 54700, 54700, 5),
 ('HaRu19287', 5, 54724, 54724, 5),
 ('HaRu19287', 5, 54884, 54884, 5),
 ('HaRu19287', 5, 54897, 54897, 5),
 ('HaRu19287', 5, 54983, 54983, 5),
 ('HaRu19287', 5, 55053, 55053, 5),
 ('SoRu38915', 1, 26133, 26133, 1),
 ('KiRu26032', 0, 12342, 12342, 0),
 ('KiRu25619', 3, 48832, 48832, 3),
 ('KiIs23853', 2, 55796, 55796, 10),
 ('AkHa00172', 2, 41191, 41191, 2),
 ('KiRu27927', 3, 33105, 33105, 3),
 ('KiRu28045', 2, 16862, 16862, 2),
 ('KiRu29614', 1, 51573, 51573, 1),
 ('KiRu25484', 1, 20447, 20447, 1),
 ('AkRu04989', 1, 34369, 34369, 1),
 ('AkKi01455', 3, 16750, 16750, 3),
 ('AkKi01455', 3, 16781, 16781, 3),
 ('AkKi01455', 3, 16787, 16787, 3),
 ('AkKi01455', 3, 16887, 16887, 3),
 ('AkKi01455', 3, 16967, 16967, 3),
 ('AkKi01455', 3, 17025, 17025, 3),
 ('AkKi01455', 3, 17124, 17124, 3),
 ('AkKi01455', 3, 17139, 17139, 3),
 ('SoIl33047', 2, 45984, 45984, 2),
 ('SoCh32025', 0, 14252, 14252, 0),
 ('KiRu28089', 0, 9134, 9134, 0),
 ('AkRu07622', 2, 18841, 18841, 2),
 ('KiRu29909', 1, 28639, 28639, 1),
 ('AmBe11266', 9, 6032, 6032, 9),
 ('AkRu03475', 1, 33630, 33630, 10),
 ('KiRu26934', 2, 44733, 44733, 2),
 ('SoRu35691', 5, 13341, 13341, 5),
 ('SoRu35691', 5, 13440, 13440, 5),
 ('SoRu35691', 5, 13482, 13482, 5),
 ('SoRu35691', 5, 13504, 13504, 5),
 ('SoRu35691', 5, 13549, 13549, 5),
 ('SoRu35691', 5, 13591, 13591, 5),
 ('SoRu35691', 5, 13742, 13742, 5),
 ('SoRu35691', 5, 13810, 13810, 5),
 ('SoMa34148', 2, 50300, 50300, 2),
 ('AmRu15860', 1, 46070, 46070, 1),
 ('SoRu38125', 5, 26141, 26141, 5),
 ('SoRu38125', 5, 26252, 26252, 5),
 ('SoRu38125', 5, 26300, 26300, 5),
 ('SoRu38125', 5, 26322, 26322, 5),
 ('SoRu38125', 5, 26358, 26358, 5),
 ('SoRu38125', 5, 26410, 26410, 5),
 ('SoRu38125', 5, 26502, 26502, 5),
 ('SoRu38125', 5, 26634, 26634, 5),
 ('AkLu02637', 9, 13812, 13812, 9),
 ('KiIs24083', 2, 28404, 28404, 10),
 ('SoRu35824', 1, 28362, 28362, 1),
 ('KiRu27806', 0, 42076, 42076, 0),
 ('AkRu03182', 3, 13651, 13651, 3),
 ('AkHa00088', 1, 12774, 12774, 1),
 ('SoRu36828', 2, 5668, 5668, 2),
 ('AkLu02438', 9, 24429, 24429, 9),
 ('SoRu38250', 6, 21140, 21140, 6),
 ('AkHa00613', 3, 20924, 20924, 3),
 ('KiMr25005', 0, 58102, 58102, 0),
 ('AkRu04428', 3, 9203, 9203, 3),
 ('SoRu35103', 5, 44051, 44051, 5),
 ('SoRu35103', 5, 44145, 44145, 5),
 ('SoRu35103', 5, 44178, 44178, 5),
 ('SoRu35103', 5, 44237, 44237, 5),
 ('SoRu35103', 5, 44338, 44338, 5),
 ('SoRu35103', 5, 44370, 44370, 5),
 ('SoRu35103', 5, 44394, 44394, 5),
 ('SoRu35103', 5, 44522, 44522, 5),
 ('SoRu36975', 0, 26255, 26255, 0),
 ('AkHa00662', 2, 52082, 52082, 2),
 ('SoCh31985', 3, 37231, 37231, 3),
 ('AmAm09631', 9, 14211, 14211, 10),
 ('SoRu37129', 0, 31642, 31642, 0),
 ('SoRu38416', 3, 49607, 49607, 3),
 ('SoRu38416', 3, 49625, 49625, 3),
 ('SoRu38416', 3, 49798, 49798, 3),
 ('SoRu38416', 3, 49817, 49817, 3),
 ('SoRu38416', 3, 49850, 49850, 3),
 ('SoRu38416', 3, 49869, 49869, 3),
 ('SoRu38416', 3, 49977, 49977, 3),
 ('SoRu38416', 3, 50037, 50037, 3),
 ('AkRu02670', 2, 8346, 8346, 2),
 ('AkHa00487', 3, 14442, 14442, 3),
 ('SoRu36186', 0, 16286, 16286, 0),
 ('AkRu03649', 2, 4101, 4101, 2),
 ('KiRu30343', 2, 51075, 51075, 10),
 ('AmRu13668', 9, 10586, 10586, 10),
 ('SoMa34044', 0, 20902, 20902, 0),
 ('AmRu14531', 9, 13172, 13172, 9),
 ('SoRu37317', 2, 50347, 50347, 2),
 ('KiIs23613', 6, 3093, 3093, 6),
 ('SoRu39288', 0, 13409, 13409, 0),
 ('AkRu07820', 3, 34009, 34009, 3),
 ('AkRu07774', 3, 24774, 24774, 3),
 ('SoBa31691', 0, 3267, 3267, 10),
 ('SoRu36385', 2, 54896, 54896, 2),
 ('KiIs24054', 9, 21978, 21978, 9),
 ('KiRu29129', 1, 32520, 32520, 1),
 ('KiHa23042', 1, 54900, 54900, 1),
 ('AkHa00459', 1, 39863, 39863, 1),
 ('SoBa31659', 3, 17354, 17354, 3),
 ('KiRu30394', 4, 6624, 6624, 4),
 ('SoKo33111', 1, 19195, 19195, 1),
 ('AkRu03429', 3, 17142, 17142, 3),
 ('KiRu26860', 0, 24912, 24912, 0),
 ('KiAm22303', 9, 56325, 56325, 9),
 ('HaRu18493', 3, 25264, 25264, 3),
 ('HaRu18608', 1, 4779, 4779, 1),
 ('SoRu35964', 2, 58643, 58643, 2),
 ('KiMr24872', 2, 47577, 47577, 2),
 ('KiAm22458', 2, 672, 672, 2),
 ('AkRu05603', 3, 54483, 54483, 3),
 ('HaRu20851', 9, 56353, 56353, 9),
 ('KiRu25343', 1, 41757, 41757, 1),
 ('SoRu36816', 3, 57218, 57218, 3),
 ('HaRu20840', 3, 43798, 43798, 3),
 ('HaRu20840', 3, 43873, 43873, 3),
 ('HaRu20840', 3, 43894, 43894, 3),
 ('HaRu20840', 3, 43914, 43914, 3),
 ('HaRu20840', 3, 44065, 44065, 3),
 ('HaRu20840', 3, 44121, 44121, 3),
 ('HaRu20840', 3, 44189, 44189, 3),
 ('HaRu20840', 3, 44278, 44278, 3),
 ('SoRu38966', 5, 3240, 3240, 5),
 ('SoRu37494', 9, 17009, 17009, 9),
 ('HaRu19176', 1, 25331, 25331, 1),
 ('AmBe11175', 3, 22982, 22982, 3),
 ('AmBe11175', 3, 23048, 23048, 3),
 ('AmBe11175', 3, 23088, 23088, 3),
 ('AmBe11175', 3, 23094, 23094, 3),
 ('AmBe11175', 3, 23115, 23115, 3),
 ('AmBe11175', 3, 23200, 23200, 3),
 ('AmBe11175', 3, 23287, 23287, 3),
 ('AmBe11175', 3, 23453, 23453, 3),
 ('HaDe16360', 1, 19732, 19732, 1),
 ('AmBe11054', 9, 8225, 8225, 9),
 ('AkRu08460', 2, 59776, 59776, 2),
 ('SoKo33124', 3, 2006, 2006, 3),
 ('SoKo33124', 3, 2107, 2107, 3),
 ('SoKo33124', 3, 2220, 2220, 3),
 ('SoKo33124', 3, 2278, 2278, 3),
 ('SoKo33124', 3, 2304, 2304, 3),
 ('SoKo33124', 3, 2330, 2330, 3),
 ('SoKo33124', 3, 2373, 2373, 3),
 ('SoKo33124', 3, 2458, 2458, 3),
 ('AkKi01211', 3, 16824, 16824, 3),
 ('SoIl32445', 2, 25386, 25386, 2),
 ('AmRu13532', 9, 39886, 39886, 9),
 ('SoRu36142', 1, 7542, 7542, 1),
 ('AkRu05020', 3, 4291, 4291, 3),
 ('HaRu18730', 1, 34773, 34773, 1),
 ('KiRu25527', 2, 30088, 30088, 2),
 ('AkRu05442', 3, 59724, 59724, 3),
 ('AkRu05207', 3, 53713, 53713, 3),
 ('AkRu05207', 3, 53800, 53800, 3),
 ('AkRu05207', 3, 53824, 53824, 3),
 ('AkRu05207', 3, 53914, 53914, 3),
 ('AkRu05207', 3, 53928, 53928, 3),
 ('AkRu05207', 3, 54036, 54036, 3),
 ('AkRu05207', 3, 54157, 54157, 3),
 ('AkRu05207', 3, 54160, 54160, 3),
 ('AmAm09844', 9, 39550, 39550, 9),
 ('AkRu04217', 3, 18145, 18145, 3),
 ('SoRu38733', 5, 16689, 16689, 5),
 ('SoBa31655', 9, 5710, 5710, 9),
 ('SoRu37392', 4, 17821, 17821, 4),
 ('SoRu37392', 4, 17894, 17894, 4),
 ('SoRu37392', 4, 18045, 18045, 4),
 ('SoRu37392', 4, 18088, 18088, 4),
 ('SoRu37392', 4, 18116, 18116, 4),
 ('SoRu37392', 4, 18215, 18215, 4),
 ('SoRu37392', 4, 18263, 18263, 4),
 ('SoRu37392', 4, 18383, 18383, 4),
 ('AkKi01238', 3, 15839, 15839, 3),
 ('AmRu14527', 3, 36952, 36952, 3),
 ('KiRu26502', 3, 9396, 9396, 3),
 ('AkRu06339', 0, 28338, 28338, 0),
 ('SoRu37920', 0, 42676, 42676, 0),
 ('AkRu02682', 2, 26484, 26484, 2),
 ('AmBe10969', 3, 39852, 39852, 3),
 ('AmBe10969', 3, 39963, 39963, 3),
 ('AmBe10969', 3, 40094, 40094, 3),
 ('AmBe10969', 3, 40134, 40134, 3),
 ('AmBe10969', 3, 40214, 40214, 3),
 ('AmBe10969', 3, 40307, 40307, 3),
 ('AmBe10969', 3, 40313, 40313, 3),
 ('AmBe10969', 3, 40414, 40414, 3),
 ('AkRu08755', 3, 19813, 19813, 3),
 ('KiRu30051', 2, 13174, 13174, 2),
 ('HaRu19054', 2, 314, 314, 2),
 ('HaRu17182', 1, 26851, 26851, 1),
 ('AmBe11275', 3, 26263, 26263, 3),
 ('AmBe11275', 3, 26302, 26302, 3),
 ('AmBe11275', 3, 26312, 26312, 3),
 ('AmBe11275', 3, 26386, 26386, 3),
 ('AmBe11275', 3, 26491, 26491, 3),
 ('AmBe11275', 3, 26575, 26575, 3),
 ('AmBe11275', 3, 26670, 26670, 3),
 ('AmBe11275', 3, 26698, 26698, 3),
 ('HaRu19036', 2, 52668, 52668, 2),
 ('KiMr24348', 2, 40090, 40090, 2),
 ('AmPw12550', 9, 28247, 28247, 9),
 ('HaRu20299', 2, 43586, 43586, 2),
 ('KiRu29119', 1, 25652, 25652, 1),
 ('AkRu03116', 3, 32365, 32365, 3),
 ('SoRu35393', 1, 23001, 23001, 1),
 ('AkLu02173', 1, 27091, 27091, 1),
 ('AkRu08283', 3, 45092, 45092, 3),
 ('KiRu28782', 3, 58809, 58809, 3),
 ('KiRu28782', 3, 58859, 58859, 3),
 ('KiRu28782', 3, 58968, 58968, 3),
 ('KiRu28782', 3, 59030, 59030, 3),
 ('KiRu28782', 3, 59062, 59062, 3),
 ('KiRu28782', 3, 59120, 59120, 3),
 ('KiRu28782', 3, 59155, 59155, 3),
 ('KiRu28782', 3, 59242, 59242, 3),
 ('AmAs10095', 3, 46365, 46365, 3),
 ('KiRu29980', 1, 5321, 5321, 1),
 ('KiRu25770', 3, 37346, 37346, 3),
 ('AmRu15634', 3, 24374, 24374, 3),
 ('AkRu07742', 2, 3469, 3469, 2),
 ('KiRu28806', 1, 26429, 26429, 1),
 ('AmAs10011', 9, 44726, 44726, 9),
 ('KiMr25056', 1, 36815, 36815, 1),
 ('HaDj16864', 1, 25972, 25972, 1),
 ('AkRu04116', 3, 53182, 53182, 10),
 ('AmPw12272', 9, 50239, 50239, 10),
 ('HaRu18271', 1, 14781, 14781, 1),
 ('HaAm16293', 3, 55255, 55255, 3),
 ('KiRu27852', 2, 30754, 30754, 2),
 ('AmAs10552', 9, 16840, 16840, 9),
 ('HaAm16112', 2, 15506, 15506, 2),
 ('KiZu30983', 3, 5702, 5702, 3),
 ('SoRu37524', 3, 59640, 59640, 10),
 ('HaYa21356', 2, 36919, 36919, 2),
 ('AkRu03754', 3, 6493, 6493, 3),
 ('SoMa34566', 2, 39478, 39478, 2),
 ('AmRu15394', 1, 15192, 15192, 1),
 ('HaRu19917', 9, 53947, 53947, 9),
 ('SoRu35762', 1, 47342, 47342, 1),
 ('AmAm09806', 9, 41269, 41269, 9),
 ('AmAm09566', 9, 37437, 37437, 9),

In [6]:
%%sql

-- It doesn't matter if your columns are in a different format,
-- because we are about to clean this up a bit. Since it is a duplicate, we can drop one of the location_id columns.
--  Let's leave record_id and rename the scores to surveyor_score and auditor_score to make it clear which scores
-- we're looking at in the results set.   PAGE(10)

SELECT
     V.location_id ,
	 V.record_id,                                          	 
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

2698 rows affected.

+-------------+-----------+---------------+----------------+
| location_id | record_id | auditor_score | employee_score |
+-------------+-----------+---------------+----------------+
|  SoRu34980  |    5185   |       1       |       1        |
|  AkRu08112  |   59367   |       3       |       3        |
|  AkLu02044  |   37379   |       0       |       0        |
|  AkHa00421  |   51627   |       3       |       3        |
|  SoRu35221  |   28758   |       0       |       0        |
|  HaAm16170  |   31048   |       1       |       1        |
|  AkRu04812  |    1513   |       3       |       3        |
|  AkRu08304  |    1218   |       3       |       3        |
|  AkRu05107  |    8322   |       2       |       2        |
|  AkRu05215  |   21160   |       3       |       10       |
+-------------+-----------+---------------+----------------+
Truncated to displaylimit of 10.

Since were joining 1620 rows of data, we want to keep track of the number of rows we get each time we run a query. We can either set the
maximum number of rows we want from "Limit to 1000 rows" to a larger number like 10000, or we can force SQL to give us all of the results, using
LIMIT 10000.

In [7]:
%%sql

-- Ok, let's analyse! A good starting point is to check if the auditor's and exployees' scores agree.
-- There are many ways to do it. We can have a WHERE clause and check if surveyor_score = auditor_score,
-- or we can subtract the two scores and check if the result is 0.  PAGE(11)
 SELECT
     V.location_id ,
	 V.record_id,                                          	 
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score,
     (true_water_source_score - subjective_quality_score) AS RESULT_SCORE
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
WHERE
    A.true_water_source_score = WAT_Q.subjective_quality_score
LIMIT 10000

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

2505 rows affected.

+-------------+-----------+---------------+----------------+--------------+
| location_id | record_id | auditor_score | employee_score | RESULT_SCORE |
+-------------+-----------+---------------+----------------+--------------+
|  SoRu34980  |    5185   |       1       |       1        |      0       |
|  AkRu08112  |   59367   |       3       |       3        |      0       |
|  AkLu02044  |   37379   |       0       |       0        |      0       |
|  AkHa00421  |   51627   |       3       |       3        |      0       |
|  SoRu35221  |   28758   |       0       |       0        |      0       |
|  HaAm16170  |   31048   |       1       |       1        |      0       |
|  AkRu04812  |    1513   |       3       |       3        |      0       |
|  AkRu08304  |    1218   |       3       |       3        |      0       |
|  AkRu05107  |    8322   |       2       |       2        |      0       |
|  HaDe16541  |   13070   |       2       |       2        |      0       |
+-------------+-----------+---------------+----------------+--------------+
Truncated to displaylimit of 10.

In [8]:
%%sql
-- I got 2505 rows right? Some of the locations were visited multiple times, so these records are duplicated here.
-- To fix it, we set visits.visit_count
-- = 1 in the WHERE clause. Make sure you reference the alias you used for visits in the join. PAGE(11)
 SELECT
     V.location_id ,
	 V.record_id,                                          	 
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score,
     (true_water_source_score - subjective_quality_score) AS RESULT_SCORE
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
WHERE
    A.true_water_source_score  <> WAT_Q.subjective_quality_score
    AND V.visit_count = 1
LIMIT 10000 
-- But that means that 102 records are incorrect. 
-- So let's look at those. I can do it by adding one character in the last query!

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

102 rows affected.

+-------------+-----------+---------------+----------------+--------------+
| location_id | record_id | auditor_score | employee_score | RESULT_SCORE |
+-------------+-----------+---------------+----------------+--------------+
|  AkRu05215  |   21160   |       3       |       10       |      -7      |
|  KiRu29290  |    7938   |       3       |       10       |      -7      |
|  KiHa22748  |   43140   |       9       |       10       |      -1      |
|  SoRu37841  |   18495   |       6       |       10       |      -4      |
|  KiRu27884  |   33931   |       1       |       10       |      -9      |
|  KiZu31170  |   17950   |       9       |       10       |      -1      |
|  KiZu31370  |   36864   |       3       |       10       |      -7      |
|  AkRu06495  |   45924   |       2       |       10       |      -8      |
|  HaRu17528  |   30524   |       1       |       10       |      -9      |
|  SoRu38331  |   13192   |       3       |       10       |      -7      |
+-------------+-----------+---------------+----------------+--------------+
Truncated to displaylimit of 10.

With the duplicates removed I now get 1518. What does this mean considering the auditor visited 1620 sites?
I think that is an excellent result. 1518/1620 = 94% of the records the auditor checked were correct!!

In [9]:
%%sql

-- So, to do this, we need to grab the type_of_water_source column from the water_source table and call it survey_source, 
-- using the source_id column to JOIN. 
-- Also select the type_of_water_source from the auditor_report table,
-- and call it auditor_source.   PAGE(13)
 
 SELECT
     V.location_id ,
	 A.type_of_water_source AS auditor_source,
     water_source.type_of_water_source AS survey_source,
	 V.record_id,                                          	 
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
JOIN
    mdd_water_services.water_source
ON
   water_source.source_id = V.source_id
WHERE
    A.true_water_source_score  <> WAT_Q.subjective_quality_score
    AND V.visit_count = 1
LIMIT 10000

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

102 rows affected.

+-------------+--------------------+--------------------+-----------+---------------+----------------+
| location_id |   auditor_source   |   survey_source    | record_id | auditor_score | employee_score |
+-------------+--------------------+--------------------+-----------+---------------+----------------+
|  AkRu05215  |        well        |        well        |   21160   |       3       |       10       |
|  KiRu29290  |     shared_tap     |     shared_tap     |    7938   |       3       |       10       |
|  KiHa22748  | tap_in_home_broken | tap_in_home_broken |   43140   |       9       |       10       |
|  SoRu37841  |     shared_tap     |     shared_tap     |   18495   |       6       |       10       |
|  KiRu27884  |        well        |        well        |   33931   |       1       |       10       |
|  KiZu31170  | tap_in_home_broken | tap_in_home_broken |   17950   |       9       |       10       |
|  KiZu31370  |     shared_tap     |     shared_tap     |   36864   |       3       |       10       |
|  AkRu06495  |        well        |        well        |   45924   |       2       |       10       |
|  HaRu17528  |        well        |        well        |   30524   |       1       |       10       |
|  SoRu38331  |     shared_tap     |     shared_tap     |   13192   |       3       |       10       |
+-------------+--------------------+--------------------+-----------+---------------+----------------+
Truncated to displaylimit of 10.

So what I can see is that the types of sources look the same! So even though the scores are wrong, the integrity of the type_of_water_source
data we analysed last time is not affected.

Once you're done, remove the columns and JOIN statement for water_sources again.
#### Linking records to employees
Next up, let's look at where these errors may have come from. At some of the locations, employees assigned scores incorrectly, and those records
ended up in this results set.

I think there are two reasons this can happen.
1. These workers are all humans and make mistakes so this is expected.
2. Unfortunately, the alternative is that someone assigned scores incorrectly on purpose!

In [10]:
%%sql

-- In either case, the employees are the source of the errors, 
-- so let's JOIN the assigned_employee_id for all the people on our list from the visits
-- table to our query. Remember, our query shows the shows the 102 incorrect records,
-- so when we join the employee data, we can see which
-- employees made these incorrect records.  PAGE(14)
 SELECT
     V.location_id ,
	 V.record_id, 
     A.type_of_water_source AS auditor_source,
     V.assigned_employee_id AS assigned_employee_id,
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
JOIN
    mdd_water_services.water_source
ON
   water_source.source_id = V.source_id
WHERE
    A.true_water_source_score  <> WAT_Q.subjective_quality_score
    AND V.visit_count = 1
LIMIT 10000

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

102 rows affected.

+-------------+-----------+--------------------+----------------------+---------------+----------------+
| location_id | record_id |   auditor_source   | assigned_employee_id | auditor_score | employee_score |
+-------------+-----------+--------------------+----------------------+---------------+----------------+
|  AkRu05215  |   21160   |        well        |          34          |       3       |       10       |
|  KiRu29290  |    7938   |     shared_tap     |          1           |       3       |       10       |
|  KiHa22748  |   43140   | tap_in_home_broken |          1           |       9       |       10       |
|  SoRu37841  |   18495   |     shared_tap     |          34          |       6       |       10       |
|  KiRu27884  |   33931   |        well        |          1           |       1       |       10       |
|  KiZu31170  |   17950   | tap_in_home_broken |          5           |       9       |       10       |
|  KiZu31370  |   36864   |     shared_tap     |          48          |       3       |       10       |
|  AkRu06495  |   45924   |        well        |          1           |       2       |       10       |
|  HaRu17528  |   30524   |        well        |          18          |       1       |       10       |
|  SoRu38331  |   13192   |     shared_tap     |          5           |       3       |       10       |
+-------------+-----------+--------------------+----------------------+---------------+----------------+
Truncated to displaylimit of 10.

In [11]:
%%sql

-- So now we can link the incorrect records to the employees who recorded them.
-- The ID's don't help us to identify them. We have employees' names
-- stored along with their IDs, 
-- so let's fetch their names from the employees table instead of the ID's.  PAGE(15)
 SELECT
     V.location_id,
	 V.record_id, 
     A.type_of_water_source AS auditor_source,
     employee.employee_name AS employee_name,
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
JOIN
    mdd_water_services.water_source
ON
   water_source.source_id = V.source_id
JOIN 
   mdd_water_services.employee AS employee
ON
  V.assigned_employee_id = employee.assigned_employee_id
  
WHERE
    A.true_water_source_score  <> WAT_Q.subjective_quality_score
    AND V.visit_count = 1
LIMIT 10000

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

102 rows affected.

+-------------+-----------+--------------------+----------------+---------------+----------------+
| location_id | record_id |   auditor_source   | employee_name  | auditor_score | employee_score |
+-------------+-----------+--------------------+----------------+---------------+----------------+
|  AkRu05215  |   21160   |        well        |   Rudo Imani   |       3       |       10       |
|  KiRu29290  |    7938   |     shared_tap     |  Bello Azibo   |       3       |       10       |
|  KiHa22748  |   43140   | tap_in_home_broken |  Bello Azibo   |       9       |       10       |
|  SoRu37841  |   18495   |     shared_tap     |   Rudo Imani   |       6       |       10       |
|  KiRu27884  |   33931   |        well        |  Bello Azibo   |       1       |       10       |
|  KiZu31170  |   17950   | tap_in_home_broken | Zuriel Matembo |       9       |       10       |
|  KiZu31370  |   36864   |     shared_tap     | Yewande Ebele  |       3       |       10       |
|  AkRu06495  |   45924   |        well        |  Bello Azibo   |       2       |       10       |
|  HaRu17528  |   30524   |        well        | Jengo Tumaini  |       1       |       10       |
|  SoRu38331  |   13192   |     shared_tap     | Zuriel Matembo |       3       |       10       |
+-------------+-----------+--------------------+----------------+---------------+----------------+
Truncated to displaylimit of 10.

Well this query is massive and complex, so maybe it is a good idea to save this as a CTE, so when we do more analysis, we can just call that CTE
like it was a table. Call it something like Incorrect_records. Once you are done, check if this query SELECT * FROM Incorrect_records, gets
the same table back.

Now that we defined Incorrect_records, we can query it like any other table.

Let's first get a unique list of employees from this table. Think back to the start of your SQL journey to answer this one. I got 17 employees.

In [12]:
%%sql

-- Well this query is massive and complex, so maybe it is a good idea to save this as a CTE, 
-- so when we do more analysis, we can just call that CTE
-- like it was a table. Call it something like Incorrect_records. Once you are done, 
-- check if this query SELECT * FROM Incorrect_records, gets
-- the same table back.  PAGE(16)

WITH Incorrect_records AS(
 SELECT
     V.location_id ,
	 V.record_id, 
     A.type_of_water_source AS auditor_source,
     employee.employee_name AS employee_name,
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
JOIN
    mdd_water_services.water_source
ON
   water_source.source_id = V.source_id
JOIN 
   mdd_water_services.employee AS employee
ON
  V.assigned_employee_id = employee.assigned_employee_id
  
WHERE
    A.true_water_source_score  <> WAT_Q.subjective_quality_score
    AND V.visit_count = 1)

SELECT
      *
FROM
    Incorrect_records
LIMIT 10000

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

102 rows affected.

+-------------+-----------+--------------------+----------------+---------------+----------------+
| location_id | record_id |   auditor_source   | employee_name  | auditor_score | employee_score |
+-------------+-----------+--------------------+----------------+---------------+----------------+
|  AkRu05215  |   21160   |        well        |   Rudo Imani   |       3       |       10       |
|  KiRu29290  |    7938   |     shared_tap     |  Bello Azibo   |       3       |       10       |
|  KiHa22748  |   43140   | tap_in_home_broken |  Bello Azibo   |       9       |       10       |
|  SoRu37841  |   18495   |     shared_tap     |   Rudo Imani   |       6       |       10       |
|  KiRu27884  |   33931   |        well        |  Bello Azibo   |       1       |       10       |
|  KiZu31170  |   17950   | tap_in_home_broken | Zuriel Matembo |       9       |       10       |
|  KiZu31370  |   36864   |     shared_tap     | Yewande Ebele  |       3       |       10       |
|  AkRu06495  |   45924   |        well        |  Bello Azibo   |       2       |       10       |
|  HaRu17528  |   30524   |        well        | Jengo Tumaini  |       1       |       10       |
|  SoRu38331  |   13192   |     shared_tap     | Zuriel Matembo |       3       |       10       |
+-------------+-----------+--------------------+----------------+---------------+----------------+
Truncated to displaylimit of 10.

In [13]:
%%sql
-- Next, let's try to calculate how many mistakes each employee made. 
-- So basically we want to count how many times their name is in
-- Incorrect_records list, and then group them by name, right?

WITH Incorrect_records AS(
 SELECT
     V.location_id ,
	 V.record_id, 
     A.type_of_water_source AS auditor_source,
     employee.employee_name AS employee_name,
     A.true_water_source_score AS auditor_score,
     WAT_Q.subjective_quality_score AS employee_score
FROM
    mdd_water_services.visits AS V
JOIN 
   mdd_water_services.water_quality AS WAT_Q
ON
    V.record_id = WAT_Q.record_id
JOIN 
	mdd_water_services.auditor_report AS A
ON 
    V.location_id = A.location_id 
JOIN
    mdd_water_services.water_source
ON
   water_source.source_id = V.source_id
JOIN 
   mdd_water_services.employee AS employee
ON
  V.assigned_employee_id = employee.assigned_employee_id
  
WHERE
    A.true_water_source_score  <> WAT_Q.subjective_quality_score
    AND V.visit_count = 1)

SELECT DISTINCT 
      employee_name,
      count(employee_name) OVER (PARTITION BY employee_name) AS number_of_mistakes
FROM
    Incorrect_records
LIMIT 10000

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

17 rows affected.

+----------------+--------------------+
| employee_name  | number_of_mistakes |
+----------------+--------------------+
|  Bello Azibo   |         26         |
|  Deka Osumare  |         1          |
|  Enitan Zuri   |         4          |
|   Farai Nia    |         4          |
|  Gamba Shani   |         3          |
| Jengo Tumaini  |         3          |
| Lalitha Kaburi |         7          |
|  Makena Thabo  |         3          |
| Malachi Mavuso |         21         |
|    Ona Sefu    |         1          |
+----------------+--------------------+
Truncated to displaylimit of 10.

Do you see a pattern there? Order the list if you can't see it yet.

It looks like some of our surveyors are making a lot of "mistakes" while many of the other surveyors are only making a few. I don't like where this is
going!

#### Gathering some evidence
Ok, so thinking about this a bit. How would we go about finding out if any of our employees are corrupt?

Let's say all employees make mistakes, if someone is corrupt, they will be making a lot of "mistakes", more than average, for example. But someone
could just be clumsy, so we should try to get more evidence...

Our auditor did say some of the things he heard on the streets were quite shady, and he recorded this in the statements column. Considering
both of these sources should give us a pretty reliable answer.

So let's try to find all of the employees who have an above-average number of mistakes. Let's break it down into steps first:
1. We have to first calculate the number of times someone's name comes up. (we just did that in the previous query). Let's call it error_count.
2. Then, we need to calculate the average number of mistakes employees made. We can do that by taking the average of the previous query's
results. Something like this:
SELECT
AVG(number_of_mistakes)
FROM
error_count;
Let's call that result avg_error_count_per_empl, which would be a scalar value.
3. Finaly we have to compare each employee's error_count with avg_error_count_per_empl. We will call this results set our suspect_list.
Remember that we can't use an aggregate result in WHERE, so we have to use avg_error_count_per_empl as a subquery.
SELECT
employee_name,
number_of_mistakes
FROM
error_count
WHERE
number_of_mistakes > (avg_error_count_per_empl);

#### 1.
Let's start by cleaning up our code a bit. First, Incorrect_records is a result we'll be using for the rest of the analysis, but it makes the
query a bit less readable. So, let's convert it to a VIEW. We can then use it as if it was a table. It will make our code much simpler to read, but, it
comes at a cost. We can add comments to CTEs in our code, so if we return to that query a year later, we can read those comments and quickly
understand what Incorrect_records represents. If we save it as a VIEW, it is not as obvious. So we should add comments in places where we
use Incorrect_records.

In [14]:
%%sql
-- So, replace WITH with CREATE VIEW like this,
-- and note that I added the statements column to this table in line 8 too:  PAGE(20)

CREATE VIEW Incorrect_records AS (
					SELECT
						auditor_report.location_id,
						visits.record_id,
						employee.employee_name,
						auditor_report.true_water_source_score AS auditor_score,
						wq.subjective_quality_score AS employee_score,
						auditor_report.statements AS statements
					FROM
						auditor_report
					JOIN
						visits
					ON 
                        auditor_report.location_id = visits.location_id
					JOIN
						water_quality AS wq
					ON 
						visits.record_id = wq.record_id
					JOIN
						employee
					ON 
						employee.assigned_employee_id = visits.assigned_employee_id
					WHERE
						visits.visit_count =1
					AND 
						auditor_report.true_water_source_score != wq.subjective_quality_score);

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

++
||
++
++

In [15]:
%%sql
select
    *
from
    Incorrect_records

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

102 rows affected.

+-------------+-----------+----------------+---------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| location_id | record_id | employee_name  | auditor_score | employee_score |                                                                                         statements                                                                                        |
+-------------+-----------+----------------+---------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  AkRu05215  |   21160   |   Rudo Imani   |       3       |       10       |                                          Villagers admired the official's visit for its respectful interactions, hard work, and genuine concern.                                          |
|  KiRu29290  |    7938   |  Bello Azibo   |       3       |       10       |                                      A young artist sketches the faces in the queue, capturing the weariness of daily hours spent waiting for water.                                      |
|  KiHa22748  |   43140   |  Bello Azibo   |       9       |       10       |                                            A young girl's hopeful eyes are clouded by mistrust, her innocence tarnished by the corrupt system.                                            |
|  SoRu37841  |   18495   |   Rudo Imani   |       6       |       10       |                           The official's respectful and diligent presence was met with heartfelt appreciation, creating a sense of closeness with the villagers.                          |
|  KiRu27884  |   33931   |  Bello Azibo   |       1       |       10       |                                           A traditional healer's empathy turns to bitterness, knowing that corrupt practices harm her community.                                          |
|  KiZu31170  |   17950   | Zuriel Matembo |       9       |       10       |                                     A community leader stood with his people, expressing concern for the water quality and the time lost in queues.","                                    |
|  KiZu31370  |   36864   | Yewande Ebele  |       3       |       10       |                                  With a keen understanding of urban challenges, the official's visit left a lasting impression of respect and commitment.                                 |
|  AkRu06495  |   45924   |  Bello Azibo   |       2       |       10       |                                        A healthcare worker in the queue expressed fears about water-borne diseases, her face etched with worry.","                                        |
|  HaRu17528  |   30524   | Jengo Tumaini  |       1       |       10       |                                    With humility and diligence, the official formed bonds with the villagers that felt like genuine family connections.                                   |
|  SoRu38331  |   13192   | Zuriel Matembo |       3       |       10       | An unsettling atmosphere surrounded the official, as villagers shared their experiences of arrogance and lack of dedication. The mention of cash exchanges only intensified their doubts. |
+-------------+-----------+----------------+---------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Truncated to displaylimit of 10.

In [16]:
%%sql
-- Next, we convert the query error_count, we made earlier, into a CTE.
-- Test it to make sure it gives the same result again, using SELECT * FROM
-- Incorrect_records. On large queries like this, it is better to build the query,
-- and test each step, because fixing errors becomes harder as the
-- query grows.  PAGE(21)

WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records
				GROUP BY
					employee_name)
-- Incorrect_records is a view that joins the audit report to the database
-- for records where the auditor and
-- employees scores are different*

-- Query
SELECT
     *
FROM 
   error_count;

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

17 rows affected.

+----------------+--------------------+
| employee_name  | number_of_mistakes |
+----------------+--------------------+
|   Rudo Imani   |         5          |
|  Bello Azibo   |         26         |
| Zuriel Matembo |         17         |
| Yewande Ebele  |         3          |
| Jengo Tumaini  |         3          |
|   Farai Nia    |         4          |
| Malachi Mavuso |         21         |
|  Makena Thabo  |         3          |
| Lalitha Kaburi |         7          |
|  Gamba Shani   |         3          |
+----------------+--------------------+
Truncated to displaylimit of 10.

In [17]:
%%sql
-- 2. Now calculate the average of the number_of_mistakes in error_count. 
-- You should get a single value.  PAGE(21)

WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records
				GROUP BY
					employee_name)
-- Incorrect_records is a view that joins the audit report to the database
-- for records where the auditor and
-- employees scores are different*

SELECT
     AVG(number_of_mistakes)     
FROM 
  error_count

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

1 rows affected.

+-------------------------+
| AVG(number_of_mistakes) |
+-------------------------+
|          6.0000         |
+-------------------------+

In [18]:
%%sql

 -- 3. To find the employees who made more mistakes than the average person,
    -- we need the employee's names, the number of mistakes each one
-- made, and filter the employees with an above-average number of mistakes.  PAGE(22)
WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records
				GROUP BY
					employee_name)

-- Query
SELECT
     employee_name,
     number_of_mistakes
FROM 
   error_count
WHERE
    number_of_mistakes > 6
GROUP BY
    employee_name;
-- These are the employees who made more mistakes, on average, than their peers, 
-- so let's have a closer look at them.

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

4 rows affected.

+----------------+--------------------+
| employee_name  | number_of_mistakes |
+----------------+--------------------+
|  Bello Azibo   |         26         |
| Zuriel Matembo |         17         |
| Malachi Mavuso |         21         |
| Lalitha Kaburi |         7          |
+----------------+--------------------+

We should look at the Incorrect_records table again, and isolate all of the records these four employees gathered. We should also look at the
statements for these records to look for patterns.

#### First,
convert the suspect_list to a CTE, so we can use it to filter the records from these four employees. Make sure you get the names of the
four "suspects", and their mistake count as a result, using SELECT employee_name FROM suspect_list.

#### You should get a column of names back. So let's just recap here...
1. We use Incorrect_records to find all of the records where the auditor and employee scores don't match.
2. We then used error_count to aggregate the data, and got the number of mistakes each employee made.
3. Finally, suspect_list retrieves the data of employees who make an above-average number of mistakes.
Now we can filter that Incorrect_records CTE to identify all of the records associated with the four employees we identified

In [19]:
%%sql

-- Now we can filter that Incorrect_records CTE to identify all of the records
-- associated with the four employees we identified. PAGE(23)

WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records

-- Incorrect_records is a view that joins the audit report to the database
-- for records where the auditor and
-- employees scores are different*

GROUP BY
	employee_name),
suspect_list AS (-- This CTE SELECTS the employees with above−average mistakes
			SELECT
				employee_name,
				number_of_mistakes
			FROM
				error_count
			WHERE
				number_of_mistakes > (SELECT 
										AVG(number_of_mistakes) 
									  FROM 
										error_count))
-- This query filters all of the records where the "corrupt" employees gathered data.
SELECT
	employee_name,
	location_id,
	statements
FROM
	Incorrect_records
WHERE
	employee_name in (
					SELECT
                       employee_name 
                    FROM 
                       suspect_list);

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

71 rows affected.

+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| employee_name  | location_id |                                                                                         statements                                                                                        |
+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  Bello Azibo   |  KiRu29290  |                                      A young artist sketches the faces in the queue, capturing the weariness of daily hours spent waiting for water.                                      |
|  Bello Azibo   |  KiHa22748  |                                            A young girl's hopeful eyes are clouded by mistrust, her innocence tarnished by the corrupt system.                                            |
|  Bello Azibo   |  KiRu27884  |                                           A traditional healer's empathy turns to bitterness, knowing that corrupt practices harm her community.                                          |
| Zuriel Matembo |  KiZu31170  |                                     A community leader stood with his people, expressing concern for the water quality and the time lost in queues.","                                    |
|  Bello Azibo   |  AkRu06495  |                                        A healthcare worker in the queue expressed fears about water-borne diseases, her face etched with worry.","                                        |
| Zuriel Matembo |  SoRu38331  | An unsettling atmosphere surrounded the official, as villagers shared their experiences of arrogance and lack of dedication. The mention of cash exchanges only intensified their doubts. |
| Malachi Mavuso |  AmAm09607  |       Villagers spoke of an unsettling encounter with an official who appeared dismissive and detached. The reference to cash transactions added to their growing sense of distrust.      |
| Zuriel Matembo |  AkHa00314  |                                    A street vendor's sales suffer from time spent waiting, her concern for the water's quality affecting her products.                                    |
| Malachi Mavuso |  KiRu26598  |                                      A teenager's dreams are tempered by reality, her future threatened by the corrupt practices she sees around her.                                     |
|  Bello Azibo   |  KiIs23853  |       Villagers' wary accounts of an official's arrogance and detachment from their concerns raised suspicions. The mention of cash changing hands further tainted their perception.      |
+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Truncated to displaylimit of 10.

In [20]:
%%sql

WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records

-- Incorrect_records is a view that joins the audit report to the database
-- for records where the auditor and
-- employees scores are different*

GROUP BY
	employee_name),
suspect_list AS (-- This CTE SELECTS the employees with above−average mistakes
			SELECT
				employee_name,
				number_of_mistakes
			FROM
				error_count
			WHERE
				number_of_mistakes > (SELECT 
										AVG(number_of_mistakes) 
									  FROM 
										error_count))
-- This query filters all of the records where the "corrupt" employees gathered data.
SELECT
	employee_name,
	location_id,
	statements
FROM
	Incorrect_records
WHERE
	employee_name in (
					SELECT
                       employee_name 
                    FROM 
                       suspect_list);

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

71 rows affected.

+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| employee_name  | location_id |                                                                                         statements                                                                                        |
+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  Bello Azibo   |  KiRu29290  |                                      A young artist sketches the faces in the queue, capturing the weariness of daily hours spent waiting for water.                                      |
|  Bello Azibo   |  KiHa22748  |                                            A young girl's hopeful eyes are clouded by mistrust, her innocence tarnished by the corrupt system.                                            |
|  Bello Azibo   |  KiRu27884  |                                           A traditional healer's empathy turns to bitterness, knowing that corrupt practices harm her community.                                          |
| Zuriel Matembo |  KiZu31170  |                                     A community leader stood with his people, expressing concern for the water quality and the time lost in queues.","                                    |
|  Bello Azibo   |  AkRu06495  |                                        A healthcare worker in the queue expressed fears about water-borne diseases, her face etched with worry.","                                        |
| Zuriel Matembo |  SoRu38331  | An unsettling atmosphere surrounded the official, as villagers shared their experiences of arrogance and lack of dedication. The mention of cash exchanges only intensified their doubts. |
| Malachi Mavuso |  AmAm09607  |       Villagers spoke of an unsettling encounter with an official who appeared dismissive and detached. The reference to cash transactions added to their growing sense of distrust.      |
| Zuriel Matembo |  AkHa00314  |                                    A street vendor's sales suffer from time spent waiting, her concern for the water's quality affecting her products.                                    |
| Malachi Mavuso |  KiRu26598  |                                      A teenager's dreams are tempered by reality, her future threatened by the corrupt practices she sees around her.                                     |
|  Bello Azibo   |  KiIs23853  |       Villagers' wary accounts of an official's arrogance and detachment from their concerns raised suspicions. The mention of cash changing hands further tainted their perception.      |
+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Truncated to displaylimit of 10.

If you have a look, you will notice some alarming statements about these four officials (look at these records: AkRu04508, AkRu07310,
KiRu29639, AmAm09607, for example. See how the word "cash" is used a lot in these statements.

#### Filter the records that refer to "cash".

Let's just do one more check to make sure...

Check if there are any employees in the Incorrect_records table with statements mentioning "cash" that are not in our suspect list. This should
be as simple as adding one word.

I get an empty result, so no one, except the four suspects, has these allegations of bribery.

So we can sum up the evidence we have for Zuriel Matembo, Malachi Mavuso, Bello Azibo and Lalitha Kaburi:
1. They all made more mistakes than their peers on average.
2. They all have incriminating statements made against them, and only them.
Keep in mind, that this is not decisive proof, but it is concerning enough that we should flag it. Pres. Naledi has worked hard to stamp out
corruption, so she would urge us to report this.

# Questions of Integrated Project: Maji Ndogo Part 3

In [21]:
%%sql

-- Q1 
-- The following query results in 2,698 rows of data being retrieved, 
-- but the auditor_report table only has 1,620 rows. 
-- Analyse the query and select the reason why this discrepancy occurs. 
-- Hint: Think about the type of relationship between our tables.


SELECT
    auditorRep.location_id,
    visitsTbl.record_id,
    Empl_Table.employee_name,
    auditorRep.true_water_source_score AS auditor_score,
    wq.subjective_quality_score AS employee_score
FROM 
    auditor_report AS auditorRep
JOIN 
    visits AS visitsTbl
ON 
  auditorRep.location_id = visitsTbl.location_id
JOIN
   water_quality AS wq
ON 
  visitsTbl.record_id = wq.record_id
JOIN
   employee as Empl_Table
ON 
  Empl_Table.assigned_employee_id = visitsTbl.assigned_employee_id;
    
    
-- -----> ANSWER: The visits table has multiple records for each location_id,  
               -- which when joined with auditor_report, 
               -- results in multiple records for each location_id.

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

2698 rows affected.

+-------------+-----------+----------------+---------------+----------------+
| location_id | record_id | employee_name  | auditor_score | employee_score |
+-------------+-----------+----------------+---------------+----------------+
|  SoRu34980  |    5185   | Yewande Ebele  |       1       |       1        |
|  AkRu08112  |   59367   |   Pili Zola    |       3       |       3        |
|  AkLu02044  |   37379   | Sanaa Tendaji  |       0       |       0        |
|  AkHa00421  |   51627   |  Harith Nyota  |       3       |       3        |
|  SoRu35221  |   28758   | Malachi Mavuso |       0       |       0        |
|  HaAm16170  |   31048   |    Ona Sefu    |       1       |       1        |
|  AkRu04812  |    1513   |  Deka Osumare  |       3       |       3        |
|  AkRu08304  |    1218   | Sanaa Tendaji  |       3       |       3        |
|  AkRu05107  |    8322   | Jengo Tumaini  |       2       |       2        |
|  AkRu05215  |   21160   |   Rudo Imani   |       3       |       10       |
+-------------+-----------+----------------+---------------+----------------+
Truncated to displaylimit of 10.

In [22]:
%%sql

-- Q2
-- What is the function of Incorrect_records in the following query?

WITH Incorrect_records AS ( -- This CTE fetches all of the records with wrong scores
SELECT
    auditorRep.location_id,
    visitsTbl.record_id,
    Empl_Table.employee_name,
    auditorRep.true_water_source_score AS auditor_score,
    wq.subjective_quality_score AS employee_score
FROM 
   auditor_report AS auditorRep
JOIN
   visits AS visitsTbl
ON 
  auditorRep.location_id = visitsTbl.location_id
JOIN
   water_quality AS wq
ON 
  visitsTbl.record_id = wq.record_id
JOIN
   employee as Empl_Table
ON 
  Empl_Table.assigned_employee_id = visitsTbl.assigned_employee_id
WHERE
  visitsTbl.visit_count =1
AND auditorRep.true_water_source_score != wq.subjective_quality_score)

SELECT
    employee_name,
    count(employee_name) AS Nunmber_of_Mistakes
FROM
    Incorrect_records
GROUP BY
     Employee_name;
-- -------------> ANSWER: Incorrect_records filters and organises records 
                       -- with different scores between auditor and employee, 
                       -- preparing a tailored dataset for the main query.

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

17 rows affected.

+----------------+---------------------+
| employee_name  | Nunmber_of_Mistakes |
+----------------+---------------------+
|   Rudo Imani   |          5          |
|  Bello Azibo   |          26         |
| Zuriel Matembo |          17         |
| Yewande Ebele  |          3          |
| Jengo Tumaini  |          3          |
|   Farai Nia    |          4          |
| Malachi Mavuso |          21         |
|  Makena Thabo  |          3          |
| Lalitha Kaburi |          7          |
|  Gamba Shani   |          3          |
+----------------+---------------------+
Truncated to displaylimit of 10.

In [23]:
%%sql

# WITH Q3


WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records

-- Incorrect_records is a view that joins the audit report to the database
-- for records where the auditor and
-- employees scores are different*

GROUP BY
	employee_name),
suspect_list AS (-- This CTE SELECTS the employees with above−average mistakes
			SELECT
				employee_name,
				number_of_mistakes
			FROM
				error_count
			WHERE
				number_of_mistakes > (SELECT 
										AVG(number_of_mistakes) 
									  FROM 
										error_count))
-- This query filters all of the records where the "corrupt" employees gathered data.
SELECT
	employee_name,
	location_id,
	statements
FROM
	Incorrect_records
WHERE
	employee_name in (
					SELECT
                       employee_name 
                    FROM 
                       suspect_list);

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

71 rows affected.

+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| employee_name  | location_id |                                                                                         statements                                                                                        |
+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  Bello Azibo   |  KiRu29290  |                                      A young artist sketches the faces in the queue, capturing the weariness of daily hours spent waiting for water.                                      |
|  Bello Azibo   |  KiHa22748  |                                            A young girl's hopeful eyes are clouded by mistrust, her innocence tarnished by the corrupt system.                                            |
|  Bello Azibo   |  KiRu27884  |                                           A traditional healer's empathy turns to bitterness, knowing that corrupt practices harm her community.                                          |
| Zuriel Matembo |  KiZu31170  |                                     A community leader stood with his people, expressing concern for the water quality and the time lost in queues.","                                    |
|  Bello Azibo   |  AkRu06495  |                                        A healthcare worker in the queue expressed fears about water-borne diseases, her face etched with worry.","                                        |
| Zuriel Matembo |  SoRu38331  | An unsettling atmosphere surrounded the official, as villagers shared their experiences of arrogance and lack of dedication. The mention of cash exchanges only intensified their doubts. |
| Malachi Mavuso |  AmAm09607  |       Villagers spoke of an unsettling encounter with an official who appeared dismissive and detached. The reference to cash transactions added to their growing sense of distrust.      |
| Zuriel Matembo |  AkHa00314  |                                    A street vendor's sales suffer from time spent waiting, her concern for the water's quality affecting her products.                                    |
| Malachi Mavuso |  KiRu26598  |                                      A teenager's dreams are tempered by reality, her future threatened by the corrupt practices she sees around her.                                     |
|  Bello Azibo   |  KiIs23853  |       Villagers' wary accounts of an official's arrogance and detachment from their concerns raised suspicions. The mention of cash changing hands further tainted their perception.      |
+----------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Truncated to displaylimit of 10.

%%sql

#### -- Q3
-- In the suspect_list CTE, a subquery is used. What type of subquery is it, and what is its purpose in the query?

suspect_list AS (
SELECT 
    employee_name,
    number_of_mistakes
FROM 
    error_count
WHERE 
    number_of_mistakes > (SELECT 
                             AVG(number_of_mistakes) 
                          FROM 
                             error_count))
##### ------> ANSWER: The subquery is a scalar subquery used to calculate the average number_of_mistakes for comparison.

%%sql

#### -- Q4
-- A colleague proposed the following CTE as an alternative to the suspect_list we used previously, but it does not give the desired results. What will be the result of this subquery?

suspect_list AS (
    SELECT
       ec1.employee_name, ec1.number_of_mistakes
    FROM 
       error_count ec1
    WHERE
        ec1.number_of_mistakes >= (
        SELECT
            AVG(ec2.number_of_mistakes)
        FROM
            error_count ec2
        WHERE
            ec2.employee_name = ec1.employee_name))
#### ----> ANSWER: The subquery is a correlated subquery that returns all of the employees that made errors.

#### -- Q5

How is the relationship between the employee table and the visits table represented in the ERD?

IF we look to ERD in MySql we will see this answer

#### ----> ANSWER: employee has a 1-to-many relationship with visits.

#### -- Q6

Which table contains the location_id as its primary key?


IF we look to ERD in MySql we will see this answer

#### ----> ANSWER: location

%%sql

#### -- Q7
-- How would you modify the Incorrect_records CTE to join the well_pollution data?

WITH Incorrect_records AS (
SELECT
    auditorRep.location_id,
    visitsTbl.record_id,
    Empl_Table.employee_name,
    auditorRep.true_water_source_score AS auditor_score,
    wq.subjective_quality_score AS employee_score,
    auditorRep.statements AS statements
FROM auditor_report AS auditorRep
JOIN visits AS visitsTbl
ON auditorRep.location_id = visitsTbl.location_id
JOIN water_quality AS wq
ON visitsTbl.record_id = wq.record_id
JOIN employee as Empl_Table
ON Empl_Table.assigned_employee_id = visitsTbl.assigned_employee_id
WHERE visitsTbl.visit_count = 1 AND auditorRep.true_water_source_score != wq.subjective_quality_score)

#### this query will give error in syntax but we can modify it

In [24]:
%%sql

# with Q7
# After modifying this syntax is true 

-- Q7
WITH Incorrect_records AS (
SELECT
    auditorRep.location_id,
    visitsTbl.record_id,
    Empl_Table.employee_name,
    auditorRep.true_water_source_score AS auditor_score,
    wq.subjective_quality_score AS employee_score,
    auditorRep.statements AS statements
FROM 
    auditor_report AS auditorRep
JOIN
    visits AS visitsTbl
ON 
    auditorRep.location_id = visitsTbl.location_id
JOIN
    water_quality AS wq
ON 
    visitsTbl.record_id = wq.record_id
JOIN
    employee as Empl_Table
ON 
    Empl_Table.assigned_employee_id = visitsTbl.assigned_employee_id
JOIN 
    well_pollution
ON
    visitsTbl.source_id = well_pollution.source_id
WHERE
    visitsTbl.visit_count =1 
AND 
    auditorRep.true_water_source_score != wq.subjective_quality_score)

SELECT
   *
FROM 
   Incorrect_records
#-- -------------> ANSWER: JOIN well_pollution ON visitsTbl.source_id = well_pollution.source_id

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

49 rows affected.

+-------------+-----------+----------------+---------------+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| location_id | record_id | employee_name  | auditor_score | employee_score |                                                                                   statements                                                                                   |
+-------------+-----------+----------------+---------------+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  AkRu05215  |   21160   |   Rudo Imani   |       3       |       10       |                                    Villagers admired the official's visit for its respectful interactions, hard work, and genuine concern.                                     |
|  KiRu27884  |   33931   |  Bello Azibo   |       1       |       10       |                                     A traditional healer's empathy turns to bitterness, knowing that corrupt practices harm her community.                                     |
|  AkRu06495  |   45924   |  Bello Azibo   |       2       |       10       |                                  A healthcare worker in the queue expressed fears about water-borne diseases, her face etched with worry.","                                   |
|  HaRu17528  |   30524   | Jengo Tumaini  |       1       |       10       |                              With humility and diligence, the official formed bonds with the villagers that felt like genuine family connections.                              |
|  KiIs23853  |   55796   |  Bello Azibo   |       2       |       10       | Villagers' wary accounts of an official's arrogance and detachment from their concerns raised suspicions. The mention of cash changing hands further tainted their perception. |
|  AkRu03475  |   33630   |  Makena Thabo  |       1       |       10       |                       Villagers spoke highly of the official's humility and dedication, underscoring their respectful approach and familial connection.                        |
|  KiIs24083  |   28404   | Lalitha Kaburi |       2       |       10       |                                 A fisherman's anger boils beneath the surface, his livelihood threatened by the corrupt who tamper with water.                                 |
|  KiRu30343  |   51075   | Zuriel Matembo |       2       |       10       |                                 A university student's studies suffer from hours in line, dreams clouded by the daily reality of dirty water.                                  |
|  AkRu04116  |   53182   | Malachi Mavuso |       3       |       10       |                                A student's ambition is fueled by the daily water struggle, his determination to overcome evident in the queue.                                 |
|  SoRu37524  |   59640   |  Enitan Zuri   |       3       |       10       |                         Villagers held the official in high esteem, praising their dedication, respect, and the familial connections they established.                         |
+-------------+-----------+----------------+---------------+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Truncated to displaylimit of 10.

#### Q8

In [25]:
%%sql

-- Q8
-- Which employee just avoided our classification of having an above-average number of mistakes? 
-- Hint: Use one of the queries we used to aggregate data from Incorrect_records.

WITH mistake_counts AS (
    SELECT
        employee_name,
        COUNT(*) AS total_mistakes
    FROM
        Incorrect_records
    GROUP BY
        employee_name
)

SELECT
    employee_name,
    AVG(total_mistakes) AS AVG_of_mistakes
FROM
    mistake_counts
GROUP BY
    employee_name
HAVING
    AVG(total_mistakes) = 5;
-- ------------------------------------> ANSWER: Rudo Imani
    
-- NOTE: AVGREGE(number_of_mistakes) = 6.00
-- NOTE: AVGREGE(number_of_mistakes) of Rudo Imani = 5.00

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

1 rows affected.

+---------------+-----------------+
| employee_name | AVG_of_mistakes |
+---------------+-----------------+
|   Rudo Imani  |      5.0000     |
+---------------+-----------------+

### Q9

Which of the following “suspects” is connected to the following civilian statement:
“Suspicion coloured villagers' descriptions of an official's aloof demeanour and apparent laziness. The reference to cash transactions casts doubt on their motives

### -- ------------------------------------> ANSWER: Lalitha Kaburi


#### Below is Justifying my Answer

In [26]:
%%sql

-- Q9 
WITH error_count AS ( -- This CTE calculates the number of mistakes each employee made
				SELECT
					employee_name,
					COUNT(employee_name) AS number_of_mistakes
				FROM
					Incorrect_records

-- Incorrect_records is a view that joins the audit report to the database
-- for records where the auditor and
-- employees scores are different*

GROUP BY
	employee_name),
suspect_list AS (-- This CTE SELECTS the employees with above−average mistakes
			SELECT
				employee_name,
				number_of_mistakes
			FROM
				error_count
			WHERE
				number_of_mistakes > (SELECT 
										AVG(number_of_mistakes) 
									  FROM 
										error_count))
-- This query filters all of the records where the "corrupt" employees gathered data.
SELECT
	employee_name,
	location_id,
	statements
FROM
	Incorrect_records
WHERE
	employee_name in (
					SELECT
                       employee_name 
                    FROM 
                       suspect_list)
AND 
   statements LIKE "%Suspicion colored villagers%"

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

1 rows affected.

+----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| employee_name  | location_id |                                                                            statements                                                                            |
+----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lalitha Kaburi |  KiRu29329  | Suspicion colored villagers' descriptions of an official's aloof demeanor and apparent laziness. The reference to cash transactions cast doubt on their motives. |
+----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Q10

In [27]:
%%sql

-- Q10

-- Consider the provided SQL query. What does it do?

SELECT
    auditorRep.location_id,
    visitsTbl.record_id,
    auditorRep.true_water_source_score AS auditor_score,
    wq.subjective_quality_score AS employee_score,
    wq.subjective_quality_score - auditorRep.true_water_source_score  AS score_diff
FROM 
    auditor_report AS auditorRep
JOIN 
    visits AS visitsTbl
ON 
    auditorRep.location_id = visitsTbl.location_id
JOIN 
    water_quality AS wq
ON 
   visitsTbl.record_id = wq.record_id
WHERE
    (wq.subjective_quality_score - auditorRep.true_water_source_score) > 9;

-- --------> ANSWER: The query retrieves the auditor records where employees 
                  -- assigned very high scores to very poor water sources.

Running query in 'mysql+pymysql://Explore:***@localhost:3306/mdd_water_services'

10 rows affected.

+-------------+-----------+---------------+----------------+------------+
| location_id | record_id | auditor_score | employee_score | score_diff |
+-------------+-----------+---------------+----------------+------------+
|  SoBa31691  |    3267   |       0       |       10       |     10     |
|  AkHa00363  |   25387   |       0       |       10       |     10     |
|  SoKo33094  |   16159   |       0       |       10       |     10     |
|  KiRu27364  |   38102   |       0       |       10       |     10     |
|  KiRu27065  |   29772   |       0       |       10       |     10     |
|  KiRu29147  |    3179   |       0       |       10       |     10     |
|  SoIl32770  |    7548   |       0       |       10       |     10     |
|  KiRu29329  |   11962   |       0       |       10       |     10     |
|  SoRu39544  |   17929   |       0       |       10       |     10     |
|  SoRu38535  |   44282   |       0       |       10       |     10     |
+-------------+-----------+---------------+----------------+------------+
Truncated to displaylimit of 10.